// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: card_identifiers.sql

package db

import (
	"context"
	"database/sql"
)

const getAllIdentifiers = `-- name: GetAllIdentifiers :many
SELECT uuid, scryfallid, scryfalloracleid, scryfallillustrationid, scryfallcardbackid, mcmid, mcmmetaid, mtgarenaid, mtgoid, mtgofoilid, multiverseid, tcgplayerproductid, tcgplayeretchedproductid, tcgplayeralternativefoilproductid, cardkingdomid, cardkingdomfoilid, cardkingdometchedid, cardsphereid, cardspherefoilid, deckboxid, mtgjsonfoilversionid, mtgjsonnonfoilversionid, mtgjsonv4id FROM cardidentifiers LIMIT ? OFFSET ?
`

type GetAllIdentifiersParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetAllIdentifiers(ctx context.Context, arg GetAllIdentifiersParams) ([]Cardidentifier, error) {
	rows, err := q.db.QueryContext(ctx, getAllIdentifiers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cardidentifier
	for rows.Next() {
		var i Cardidentifier
		if err := rows.Scan(
			&i.Uuid,
			&i.Scryfallid,
			&i.Scryfalloracleid,
			&i.Scryfallillustrationid,
			&i.Scryfallcardbackid,
			&i.Mcmid,
			&i.Mcmmetaid,
			&i.Mtgarenaid,
			&i.Mtgoid,
			&i.Mtgofoilid,
			&i.Multiverseid,
			&i.Tcgplayerproductid,
			&i.Tcgplayeretchedproductid,
			&i.Tcgplayeralternativefoilproductid,
			&i.Cardkingdomid,
			&i.Cardkingdomfoilid,
			&i.Cardkingdometchedid,
			&i.Cardsphereid,
			&i.Cardspherefoilid,
			&i.Deckboxid,
			&i.Mtgjsonfoilversionid,
			&i.Mtgjsonnonfoilversionid,
			&i.Mtgjsonv4id,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardByNameAndSetCode = `-- name: GetCardByNameAndSetCode :one
SELECT c.uuid, c.name, c.setcode, c.number, ci.scryfallid
FROM cards c
JOIN cardidentifiers ci ON c.uuid = ci.uuid
WHERE c.name = ? AND c.setcode = ?
LIMIT 1
`

type GetCardByNameAndSetCodeParams struct {
	Name    sql.NullString
	Setcode sql.NullString
}

type GetCardByNameAndSetCodeRow struct {
	Uuid       sql.NullString
	Name       sql.NullString
	Setcode    sql.NullString
	Number     sql.NullString
	Scryfallid sql.NullString
}

func (q *Queries) GetCardByNameAndSetCode(ctx context.Context, arg GetCardByNameAndSetCodeParams) (GetCardByNameAndSetCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getCardByNameAndSetCode, arg.Name, arg.Setcode)
	var i GetCardByNameAndSetCodeRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Setcode,
		&i.Number,
		&i.Scryfallid,
	)
	return i, err
}

const getCardByNameSetCodeAndNumber = `-- name: GetCardByNameSetCodeAndNumber :one
SELECT c.uuid, c.name, c.setcode, c.number, ci.scryfallid
FROM cards c
JOIN cardidentifiers ci ON c.uuid = ci.uuid
WHERE c.name = ? AND c.setcode = ? AND c.number = ?
`

type GetCardByNameSetCodeAndNumberParams struct {
	Name    sql.NullString
	Setcode sql.NullString
	Number  sql.NullString
}

type GetCardByNameSetCodeAndNumberRow struct {
	Uuid       sql.NullString
	Name       sql.NullString
	Setcode    sql.NullString
	Number     sql.NullString
	Scryfallid sql.NullString
}

func (q *Queries) GetCardByNameSetCodeAndNumber(ctx context.Context, arg GetCardByNameSetCodeAndNumberParams) (GetCardByNameSetCodeAndNumberRow, error) {
	row := q.db.QueryRowContext(ctx, getCardByNameSetCodeAndNumber, arg.Name, arg.Setcode, arg.Number)
	var i GetCardByNameSetCodeAndNumberRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Setcode,
		&i.Number,
		&i.Scryfallid,
	)
	return i, err
}

const getIdentifierByScryfallId = `-- name: GetIdentifierByScryfallId :one
SELECT uuid, scryfallid, scryfalloracleid, scryfallillustrationid, scryfallcardbackid, mcmid, mcmmetaid, mtgarenaid, mtgoid, mtgofoilid, multiverseid, tcgplayerproductid, tcgplayeretchedproductid, tcgplayeralternativefoilproductid, cardkingdomid, cardkingdomfoilid, cardkingdometchedid, cardsphereid, cardspherefoilid, deckboxid, mtgjsonfoilversionid, mtgjsonnonfoilversionid, mtgjsonv4id FROM cardidentifiers WHERE scryfallid = ?
`

func (q *Queries) GetIdentifierByScryfallId(ctx context.Context, scryfallid sql.NullString) (Cardidentifier, error) {
	row := q.db.QueryRowContext(ctx, getIdentifierByScryfallId, scryfallid)
	var i Cardidentifier
	err := row.Scan(
		&i.Uuid,
		&i.Scryfallid,
		&i.Scryfalloracleid,
		&i.Scryfallillustrationid,
		&i.Scryfallcardbackid,
		&i.Mcmid,
		&i.Mcmmetaid,
		&i.Mtgarenaid,
		&i.Mtgoid,
		&i.Mtgofoilid,
		&i.Multiverseid,
		&i.Tcgplayerproductid,
		&i.Tcgplayeretchedproductid,
		&i.Tcgplayeralternativefoilproductid,
		&i.Cardkingdomid,
		&i.Cardkingdomfoilid,
		&i.Cardkingdometchedid,
		&i.Cardsphereid,
		&i.Cardspherefoilid,
		&i.Deckboxid,
		&i.Mtgjsonfoilversionid,
		&i.Mtgjsonnonfoilversionid,
		&i.Mtgjsonv4id,
	)
	return i, err
}

const getIdentifierByUuid = `-- name: GetIdentifierByUuid :one
SELECT uuid, scryfallid, scryfalloracleid, scryfallillustrationid, scryfallcardbackid, mcmid, mcmmetaid, mtgarenaid, mtgoid, mtgofoilid, multiverseid, tcgplayerproductid, tcgplayeretchedproductid, tcgplayeralternativefoilproductid, cardkingdomid, cardkingdomfoilid, cardkingdometchedid, cardsphereid, cardspherefoilid, deckboxid, mtgjsonfoilversionid, mtgjsonnonfoilversionid, mtgjsonv4id FROM cardidentifiers WHERE uuid = ?
`

func (q *Queries) GetIdentifierByUuid(ctx context.Context, uuid sql.NullString) (Cardidentifier, error) {
	row := q.db.QueryRowContext(ctx, getIdentifierByUuid, uuid)
	var i Cardidentifier
	err := row.Scan(
		&i.Uuid,
		&i.Scryfallid,
		&i.Scryfalloracleid,
		&i.Scryfallillustrationid,
		&i.Scryfallcardbackid,
		&i.Mcmid,
		&i.Mcmmetaid,
		&i.Mtgarenaid,
		&i.Mtgoid,
		&i.Mtgofoilid,
		&i.Multiverseid,
		&i.Tcgplayerproductid,
		&i.Tcgplayeretchedproductid,
		&i.Tcgplayeralternativefoilproductid,
		&i.Cardkingdomid,
		&i.Cardkingdomfoilid,
		&i.Cardkingdometchedid,
		&i.Cardsphereid,
		&i.Cardspherefoilid,
		&i.Deckboxid,
		&i.Mtgjsonfoilversionid,
		&i.Mtgjsonnonfoilversionid,
		&i.Mtgjsonv4id,
	)
	return i, err
}

const getIdentifiersByUuidList = `-- name: GetIdentifiersByUuidList :many
SELECT uuid, scryfallid, scryfalloracleid, scryfallillustrationid, scryfallcardbackid, mcmid, mcmmetaid, mtgarenaid, mtgoid, mtgofoilid, multiverseid, tcgplayerproductid, tcgplayeretchedproductid, tcgplayeralternativefoilproductid, cardkingdomid, cardkingdomfoilid, cardkingdometchedid, cardsphereid, cardspherefoilid, deckboxid, mtgjsonfoilversionid, mtgjsonnonfoilversionid, mtgjsonv4id FROM cardidentifiers WHERE uuid IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type GetIdentifiersByUuidListParams struct {
	Uuid    sql.NullString
	Uuid_2  sql.NullString
	Uuid_3  sql.NullString
	Uuid_4  sql.NullString
	Uuid_5  sql.NullString
	Uuid_6  sql.NullString
	Uuid_7  sql.NullString
	Uuid_8  sql.NullString
	Uuid_9  sql.NullString
	Uuid_10 sql.NullString
}

func (q *Queries) GetIdentifiersByUuidList(ctx context.Context, arg GetIdentifiersByUuidListParams) ([]Cardidentifier, error) {
	rows, err := q.db.QueryContext(ctx, getIdentifiersByUuidList,
		arg.Uuid,
		arg.Uuid_2,
		arg.Uuid_3,
		arg.Uuid_4,
		arg.Uuid_5,
		arg.Uuid_6,
		arg.Uuid_7,
		arg.Uuid_8,
		arg.Uuid_9,
		arg.Uuid_10,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cardidentifier
	for rows.Next() {
		var i Cardidentifier
		if err := rows.Scan(
			&i.Uuid,
			&i.Scryfallid,
			&i.Scryfalloracleid,
			&i.Scryfallillustrationid,
			&i.Scryfallcardbackid,
			&i.Mcmid,
			&i.Mcmmetaid,
			&i.Mtgarenaid,
			&i.Mtgoid,
			&i.Mtgofoilid,
			&i.Multiverseid,
			&i.Tcgplayerproductid,
			&i.Tcgplayeretchedproductid,
			&i.Tcgplayeralternativefoilproductid,
			&i.Cardkingdomid,
			&i.Cardkingdomfoilid,
			&i.Cardkingdometchedid,
			&i.Cardsphereid,
			&i.Cardspherefoilid,
			&i.Deckboxid,
			&i.Mtgjsonfoilversionid,
			&i.Mtgjsonnonfoilversionid,
			&i.Mtgjsonv4id,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
