// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: card_identifiers.sql

package db

import (
	"context"
	"database/sql"
)

const getAllIdentifiers = `-- name: GetAllIdentifiers :many
SELECT uuid, scryfallid, scryfalloracleid, scryfallillustrationid, scryfallcardbackid, mcmid, mcmmetaid, mtgarenaid, mtgoid, mtgofoilid, multiverseid, tcgplayerproductid, tcgplayeretchedproductid, tcgplayeralternativefoilproductid, cardkingdomid, cardkingdomfoilid, cardkingdometchedid, cardsphereid, cardspherefoilid, deckboxid, mtgjsonfoilversionid, mtgjsonnonfoilversionid, mtgjsonv4id FROM cardidentifiers LIMIT ? OFFSET ?
`

type GetAllIdentifiersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetAllIdentifiers(ctx context.Context, arg GetAllIdentifiersParams) ([]Cardidentifier, error) {
	rows, err := q.db.QueryContext(ctx, getAllIdentifiers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cardidentifier{}
	for rows.Next() {
		var i Cardidentifier
		if err := rows.Scan(
			&i.Uuid,
			&i.Scryfallid,
			&i.Scryfalloracleid,
			&i.Scryfallillustrationid,
			&i.Scryfallcardbackid,
			&i.Mcmid,
			&i.Mcmmetaid,
			&i.Mtgarenaid,
			&i.Mtgoid,
			&i.Mtgofoilid,
			&i.Multiverseid,
			&i.Tcgplayerproductid,
			&i.Tcgplayeretchedproductid,
			&i.Tcgplayeralternativefoilproductid,
			&i.Cardkingdomid,
			&i.Cardkingdomfoilid,
			&i.Cardkingdometchedid,
			&i.Cardsphereid,
			&i.Cardspherefoilid,
			&i.Deckboxid,
			&i.Mtgjsonfoilversionid,
			&i.Mtgjsonnonfoilversionid,
			&i.Mtgjsonv4id,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdentifierByScryfallId = `-- name: GetIdentifierByScryfallId :one
SELECT uuid, scryfallid, scryfalloracleid, scryfallillustrationid, scryfallcardbackid, mcmid, mcmmetaid, mtgarenaid, mtgoid, mtgofoilid, multiverseid, tcgplayerproductid, tcgplayeretchedproductid, tcgplayeralternativefoilproductid, cardkingdomid, cardkingdomfoilid, cardkingdometchedid, cardsphereid, cardspherefoilid, deckboxid, mtgjsonfoilversionid, mtgjsonnonfoilversionid, mtgjsonv4id FROM cardidentifiers WHERE scryfallid = ?
`

func (q *Queries) GetIdentifierByScryfallId(ctx context.Context, scryfallid sql.NullString) (Cardidentifier, error) {
	row := q.db.QueryRowContext(ctx, getIdentifierByScryfallId, scryfallid)
	var i Cardidentifier
	err := row.Scan(
		&i.Uuid,
		&i.Scryfallid,
		&i.Scryfalloracleid,
		&i.Scryfallillustrationid,
		&i.Scryfallcardbackid,
		&i.Mcmid,
		&i.Mcmmetaid,
		&i.Mtgarenaid,
		&i.Mtgoid,
		&i.Mtgofoilid,
		&i.Multiverseid,
		&i.Tcgplayerproductid,
		&i.Tcgplayeretchedproductid,
		&i.Tcgplayeralternativefoilproductid,
		&i.Cardkingdomid,
		&i.Cardkingdomfoilid,
		&i.Cardkingdometchedid,
		&i.Cardsphereid,
		&i.Cardspherefoilid,
		&i.Deckboxid,
		&i.Mtgjsonfoilversionid,
		&i.Mtgjsonnonfoilversionid,
		&i.Mtgjsonv4id,
	)
	return i, err
}

const getIdentifierByUuid = `-- name: GetIdentifierByUuid :one
SELECT uuid, scryfallid, scryfalloracleid, scryfallillustrationid, scryfallcardbackid, mcmid, mcmmetaid, mtgarenaid, mtgoid, mtgofoilid, multiverseid, tcgplayerproductid, tcgplayeretchedproductid, tcgplayeralternativefoilproductid, cardkingdomid, cardkingdomfoilid, cardkingdometchedid, cardsphereid, cardspherefoilid, deckboxid, mtgjsonfoilversionid, mtgjsonnonfoilversionid, mtgjsonv4id FROM cardidentifiers WHERE uuid = ?
`

func (q *Queries) GetIdentifierByUuid(ctx context.Context, uuid sql.NullString) (Cardidentifier, error) {
	row := q.db.QueryRowContext(ctx, getIdentifierByUuid, uuid)
	var i Cardidentifier
	err := row.Scan(
		&i.Uuid,
		&i.Scryfallid,
		&i.Scryfalloracleid,
		&i.Scryfallillustrationid,
		&i.Scryfallcardbackid,
		&i.Mcmid,
		&i.Mcmmetaid,
		&i.Mtgarenaid,
		&i.Mtgoid,
		&i.Mtgofoilid,
		&i.Multiverseid,
		&i.Tcgplayerproductid,
		&i.Tcgplayeretchedproductid,
		&i.Tcgplayeralternativefoilproductid,
		&i.Cardkingdomid,
		&i.Cardkingdomfoilid,
		&i.Cardkingdometchedid,
		&i.Cardsphereid,
		&i.Cardspherefoilid,
		&i.Deckboxid,
		&i.Mtgjsonfoilversionid,
		&i.Mtgjsonnonfoilversionid,
		&i.Mtgjsonv4id,
	)
	return i, err
}

const getIdentifiersByUuidList = `-- name: GetIdentifiersByUuidList :many
SELECT uuid, scryfallid, scryfalloracleid, scryfallillustrationid, scryfallcardbackid, mcmid, mcmmetaid, mtgarenaid, mtgoid, mtgofoilid, multiverseid, tcgplayerproductid, tcgplayeretchedproductid, tcgplayeralternativefoilproductid, cardkingdomid, cardkingdomfoilid, cardkingdometchedid, cardsphereid, cardspherefoilid, deckboxid, mtgjsonfoilversionid, mtgjsonnonfoilversionid, mtgjsonv4id FROM cardidentifiers WHERE uuid IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type GetIdentifiersByUuidListParams struct {
	Uuid    sql.NullString `json:"uuid"`
	Uuid_2  sql.NullString `json:"uuid_2"`
	Uuid_3  sql.NullString `json:"uuid_3"`
	Uuid_4  sql.NullString `json:"uuid_4"`
	Uuid_5  sql.NullString `json:"uuid_5"`
	Uuid_6  sql.NullString `json:"uuid_6"`
	Uuid_7  sql.NullString `json:"uuid_7"`
	Uuid_8  sql.NullString `json:"uuid_8"`
	Uuid_9  sql.NullString `json:"uuid_9"`
	Uuid_10 sql.NullString `json:"uuid_10"`
}

func (q *Queries) GetIdentifiersByUuidList(ctx context.Context, arg GetIdentifiersByUuidListParams) ([]Cardidentifier, error) {
	rows, err := q.db.QueryContext(ctx, getIdentifiersByUuidList,
		arg.Uuid,
		arg.Uuid_2,
		arg.Uuid_3,
		arg.Uuid_4,
		arg.Uuid_5,
		arg.Uuid_6,
		arg.Uuid_7,
		arg.Uuid_8,
		arg.Uuid_9,
		arg.Uuid_10,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cardidentifier{}
	for rows.Next() {
		var i Cardidentifier
		if err := rows.Scan(
			&i.Uuid,
			&i.Scryfallid,
			&i.Scryfalloracleid,
			&i.Scryfallillustrationid,
			&i.Scryfallcardbackid,
			&i.Mcmid,
			&i.Mcmmetaid,
			&i.Mtgarenaid,
			&i.Mtgoid,
			&i.Mtgofoilid,
			&i.Multiverseid,
			&i.Tcgplayerproductid,
			&i.Tcgplayeretchedproductid,
			&i.Tcgplayeralternativefoilproductid,
			&i.Cardkingdomid,
			&i.Cardkingdomfoilid,
			&i.Cardkingdometchedid,
			&i.Cardsphereid,
			&i.Cardspherefoilid,
			&i.Deckboxid,
			&i.Mtgjsonfoilversionid,
			&i.Mtgjsonnonfoilversionid,
			&i.Mtgjsonv4id,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
