// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package db

import (
	"context"
	"database/sql"
)

const countCards = `-- name: CountCards :one
SELECT COUNT(*) as count FROM cards
`

func (q *Queries) CountCards(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCards)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCardByName = `-- name: GetCardByName :many
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards WHERE name LIKE ?
`

func (q *Queries) GetCardByName(ctx context.Context, name sql.NullString) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getCardByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.Artist,
			&i.Artistids,
			&i.Asciiname,
			&i.Attractionlights,
			&i.Availability,
			&i.Boostertypes,
			&i.Bordercolor,
			&i.Cardparts,
			&i.Coloridentity,
			&i.Colorindicator,
			&i.Colors,
			&i.Defense,
			&i.Dueldeck,
			&i.Edhrecrank,
			&i.Edhrecsaltiness,
			&i.Faceconvertedmanacost,
			&i.Faceflavorname,
			&i.Facemanavalue,
			&i.Facename,
			&i.Faceprintedname,
			&i.Finishes,
			&i.Flavorname,
			&i.Flavortext,
			&i.Frameeffects,
			&i.Frameversion,
			&i.Hand,
			&i.Hasalternativedecklimit,
			&i.Hascontentwarning,
			&i.Isalternative,
			&i.Isfullart,
			&i.Isfunny,
			&i.Isgamechanger,
			&i.Isonlineonly,
			&i.Isoversized,
			&i.Ispromo,
			&i.Isrebalanced,
			&i.Isreprint,
			&i.Isreserved,
			&i.Isstoryspotlight,
			&i.Istextless,
			&i.Istimeshifted,
			&i.Keywords,
			&i.Language,
			&i.Layout,
			&i.Leadershipskills,
			&i.Life,
			&i.Loyalty,
			&i.Manacost,
			&i.Manavalue,
			&i.Name,
			&i.Number,
			&i.Originalprintings,
			&i.Originalreleasedate,
			&i.Originaltext,
			&i.Otherfaceids,
			&i.Power,
			&i.Printedname,
			&i.Printedtext,
			&i.Printedtype,
			&i.Printings,
			&i.Producedmana,
			&i.Promotypes,
			&i.Rarity,
			&i.Rebalancedprintings,
			&i.Relatedcards,
			&i.Securitystamp,
			&i.Setcode,
			&i.Side,
			&i.Signature,
			&i.Skuids,
			&i.Sourceproducts,
			&i.Subsets,
			&i.Subtypes,
			&i.Supertypes,
			&i.Text,
			&i.Toughness,
			&i.Type,
			&i.Types,
			&i.Uuid,
			&i.Variations,
			&i.Watermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardByUuid = `-- name: GetCardByUuid :one
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards WHERE uuid = ?
`

func (q *Queries) GetCardByUuid(ctx context.Context, uuid sql.NullString) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCardByUuid, uuid)
	var i Card
	err := row.Scan(
		&i.Artist,
		&i.Artistids,
		&i.Asciiname,
		&i.Attractionlights,
		&i.Availability,
		&i.Boostertypes,
		&i.Bordercolor,
		&i.Cardparts,
		&i.Coloridentity,
		&i.Colorindicator,
		&i.Colors,
		&i.Defense,
		&i.Dueldeck,
		&i.Edhrecrank,
		&i.Edhrecsaltiness,
		&i.Faceconvertedmanacost,
		&i.Faceflavorname,
		&i.Facemanavalue,
		&i.Facename,
		&i.Faceprintedname,
		&i.Finishes,
		&i.Flavorname,
		&i.Flavortext,
		&i.Frameeffects,
		&i.Frameversion,
		&i.Hand,
		&i.Hasalternativedecklimit,
		&i.Hascontentwarning,
		&i.Isalternative,
		&i.Isfullart,
		&i.Isfunny,
		&i.Isgamechanger,
		&i.Isonlineonly,
		&i.Isoversized,
		&i.Ispromo,
		&i.Isrebalanced,
		&i.Isreprint,
		&i.Isreserved,
		&i.Isstoryspotlight,
		&i.Istextless,
		&i.Istimeshifted,
		&i.Keywords,
		&i.Language,
		&i.Layout,
		&i.Leadershipskills,
		&i.Life,
		&i.Loyalty,
		&i.Manacost,
		&i.Manavalue,
		&i.Name,
		&i.Number,
		&i.Originalprintings,
		&i.Originalreleasedate,
		&i.Originaltext,
		&i.Otherfaceids,
		&i.Power,
		&i.Printedname,
		&i.Printedtext,
		&i.Printedtype,
		&i.Printings,
		&i.Producedmana,
		&i.Promotypes,
		&i.Rarity,
		&i.Rebalancedprintings,
		&i.Relatedcards,
		&i.Securitystamp,
		&i.Setcode,
		&i.Side,
		&i.Signature,
		&i.Skuids,
		&i.Sourceproducts,
		&i.Subsets,
		&i.Subtypes,
		&i.Supertypes,
		&i.Text,
		&i.Toughness,
		&i.Type,
		&i.Types,
		&i.Uuid,
		&i.Variations,
		&i.Watermark,
	)
	return i, err
}

const getCardsByColor = `-- name: GetCardsByColor :many
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards WHERE colors LIKE ? LIMIT ? OFFSET ?
`

type GetCardsByColorParams struct {
	Colors sql.NullString `json:"colors"`
	Limit  int64          `json:"limit"`
	Offset int64          `json:"offset"`
}

func (q *Queries) GetCardsByColor(ctx context.Context, arg GetCardsByColorParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getCardsByColor, arg.Colors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.Artist,
			&i.Artistids,
			&i.Asciiname,
			&i.Attractionlights,
			&i.Availability,
			&i.Boostertypes,
			&i.Bordercolor,
			&i.Cardparts,
			&i.Coloridentity,
			&i.Colorindicator,
			&i.Colors,
			&i.Defense,
			&i.Dueldeck,
			&i.Edhrecrank,
			&i.Edhrecsaltiness,
			&i.Faceconvertedmanacost,
			&i.Faceflavorname,
			&i.Facemanavalue,
			&i.Facename,
			&i.Faceprintedname,
			&i.Finishes,
			&i.Flavorname,
			&i.Flavortext,
			&i.Frameeffects,
			&i.Frameversion,
			&i.Hand,
			&i.Hasalternativedecklimit,
			&i.Hascontentwarning,
			&i.Isalternative,
			&i.Isfullart,
			&i.Isfunny,
			&i.Isgamechanger,
			&i.Isonlineonly,
			&i.Isoversized,
			&i.Ispromo,
			&i.Isrebalanced,
			&i.Isreprint,
			&i.Isreserved,
			&i.Isstoryspotlight,
			&i.Istextless,
			&i.Istimeshifted,
			&i.Keywords,
			&i.Language,
			&i.Layout,
			&i.Leadershipskills,
			&i.Life,
			&i.Loyalty,
			&i.Manacost,
			&i.Manavalue,
			&i.Name,
			&i.Number,
			&i.Originalprintings,
			&i.Originalreleasedate,
			&i.Originaltext,
			&i.Otherfaceids,
			&i.Power,
			&i.Printedname,
			&i.Printedtext,
			&i.Printedtype,
			&i.Printings,
			&i.Producedmana,
			&i.Promotypes,
			&i.Rarity,
			&i.Rebalancedprintings,
			&i.Relatedcards,
			&i.Securitystamp,
			&i.Setcode,
			&i.Side,
			&i.Signature,
			&i.Skuids,
			&i.Sourceproducts,
			&i.Subsets,
			&i.Subtypes,
			&i.Supertypes,
			&i.Text,
			&i.Toughness,
			&i.Type,
			&i.Types,
			&i.Uuid,
			&i.Variations,
			&i.Watermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardsByManaValue = `-- name: GetCardsByManaValue :many
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards WHERE manavalue = ? LIMIT ? OFFSET ?
`

type GetCardsByManaValueParams struct {
	Manavalue sql.NullFloat64 `json:"manavalue"`
	Limit     int64           `json:"limit"`
	Offset    int64           `json:"offset"`
}

func (q *Queries) GetCardsByManaValue(ctx context.Context, arg GetCardsByManaValueParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getCardsByManaValue, arg.Manavalue, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.Artist,
			&i.Artistids,
			&i.Asciiname,
			&i.Attractionlights,
			&i.Availability,
			&i.Boostertypes,
			&i.Bordercolor,
			&i.Cardparts,
			&i.Coloridentity,
			&i.Colorindicator,
			&i.Colors,
			&i.Defense,
			&i.Dueldeck,
			&i.Edhrecrank,
			&i.Edhrecsaltiness,
			&i.Faceconvertedmanacost,
			&i.Faceflavorname,
			&i.Facemanavalue,
			&i.Facename,
			&i.Faceprintedname,
			&i.Finishes,
			&i.Flavorname,
			&i.Flavortext,
			&i.Frameeffects,
			&i.Frameversion,
			&i.Hand,
			&i.Hasalternativedecklimit,
			&i.Hascontentwarning,
			&i.Isalternative,
			&i.Isfullart,
			&i.Isfunny,
			&i.Isgamechanger,
			&i.Isonlineonly,
			&i.Isoversized,
			&i.Ispromo,
			&i.Isrebalanced,
			&i.Isreprint,
			&i.Isreserved,
			&i.Isstoryspotlight,
			&i.Istextless,
			&i.Istimeshifted,
			&i.Keywords,
			&i.Language,
			&i.Layout,
			&i.Leadershipskills,
			&i.Life,
			&i.Loyalty,
			&i.Manacost,
			&i.Manavalue,
			&i.Name,
			&i.Number,
			&i.Originalprintings,
			&i.Originalreleasedate,
			&i.Originaltext,
			&i.Otherfaceids,
			&i.Power,
			&i.Printedname,
			&i.Printedtext,
			&i.Printedtype,
			&i.Printings,
			&i.Producedmana,
			&i.Promotypes,
			&i.Rarity,
			&i.Rebalancedprintings,
			&i.Relatedcards,
			&i.Securitystamp,
			&i.Setcode,
			&i.Side,
			&i.Signature,
			&i.Skuids,
			&i.Sourceproducts,
			&i.Subsets,
			&i.Subtypes,
			&i.Supertypes,
			&i.Text,
			&i.Toughness,
			&i.Type,
			&i.Types,
			&i.Uuid,
			&i.Variations,
			&i.Watermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardsByRarity = `-- name: GetCardsByRarity :many
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards WHERE rarity = ? LIMIT ? OFFSET ?
`

type GetCardsByRarityParams struct {
	Rarity sql.NullString `json:"rarity"`
	Limit  int64          `json:"limit"`
	Offset int64          `json:"offset"`
}

func (q *Queries) GetCardsByRarity(ctx context.Context, arg GetCardsByRarityParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getCardsByRarity, arg.Rarity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.Artist,
			&i.Artistids,
			&i.Asciiname,
			&i.Attractionlights,
			&i.Availability,
			&i.Boostertypes,
			&i.Bordercolor,
			&i.Cardparts,
			&i.Coloridentity,
			&i.Colorindicator,
			&i.Colors,
			&i.Defense,
			&i.Dueldeck,
			&i.Edhrecrank,
			&i.Edhrecsaltiness,
			&i.Faceconvertedmanacost,
			&i.Faceflavorname,
			&i.Facemanavalue,
			&i.Facename,
			&i.Faceprintedname,
			&i.Finishes,
			&i.Flavorname,
			&i.Flavortext,
			&i.Frameeffects,
			&i.Frameversion,
			&i.Hand,
			&i.Hasalternativedecklimit,
			&i.Hascontentwarning,
			&i.Isalternative,
			&i.Isfullart,
			&i.Isfunny,
			&i.Isgamechanger,
			&i.Isonlineonly,
			&i.Isoversized,
			&i.Ispromo,
			&i.Isrebalanced,
			&i.Isreprint,
			&i.Isreserved,
			&i.Isstoryspotlight,
			&i.Istextless,
			&i.Istimeshifted,
			&i.Keywords,
			&i.Language,
			&i.Layout,
			&i.Leadershipskills,
			&i.Life,
			&i.Loyalty,
			&i.Manacost,
			&i.Manavalue,
			&i.Name,
			&i.Number,
			&i.Originalprintings,
			&i.Originalreleasedate,
			&i.Originaltext,
			&i.Otherfaceids,
			&i.Power,
			&i.Printedname,
			&i.Printedtext,
			&i.Printedtype,
			&i.Printings,
			&i.Producedmana,
			&i.Promotypes,
			&i.Rarity,
			&i.Rebalancedprintings,
			&i.Relatedcards,
			&i.Securitystamp,
			&i.Setcode,
			&i.Side,
			&i.Signature,
			&i.Skuids,
			&i.Sourceproducts,
			&i.Subsets,
			&i.Subtypes,
			&i.Supertypes,
			&i.Text,
			&i.Toughness,
			&i.Type,
			&i.Types,
			&i.Uuid,
			&i.Variations,
			&i.Watermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardsBySetCode = `-- name: GetCardsBySetCode :many
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards WHERE setcode = ?
`

func (q *Queries) GetCardsBySetCode(ctx context.Context, setcode sql.NullString) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getCardsBySetCode, setcode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.Artist,
			&i.Artistids,
			&i.Asciiname,
			&i.Attractionlights,
			&i.Availability,
			&i.Boostertypes,
			&i.Bordercolor,
			&i.Cardparts,
			&i.Coloridentity,
			&i.Colorindicator,
			&i.Colors,
			&i.Defense,
			&i.Dueldeck,
			&i.Edhrecrank,
			&i.Edhrecsaltiness,
			&i.Faceconvertedmanacost,
			&i.Faceflavorname,
			&i.Facemanavalue,
			&i.Facename,
			&i.Faceprintedname,
			&i.Finishes,
			&i.Flavorname,
			&i.Flavortext,
			&i.Frameeffects,
			&i.Frameversion,
			&i.Hand,
			&i.Hasalternativedecklimit,
			&i.Hascontentwarning,
			&i.Isalternative,
			&i.Isfullart,
			&i.Isfunny,
			&i.Isgamechanger,
			&i.Isonlineonly,
			&i.Isoversized,
			&i.Ispromo,
			&i.Isrebalanced,
			&i.Isreprint,
			&i.Isreserved,
			&i.Isstoryspotlight,
			&i.Istextless,
			&i.Istimeshifted,
			&i.Keywords,
			&i.Language,
			&i.Layout,
			&i.Leadershipskills,
			&i.Life,
			&i.Loyalty,
			&i.Manacost,
			&i.Manavalue,
			&i.Name,
			&i.Number,
			&i.Originalprintings,
			&i.Originalreleasedate,
			&i.Originaltext,
			&i.Otherfaceids,
			&i.Power,
			&i.Printedname,
			&i.Printedtext,
			&i.Printedtype,
			&i.Printings,
			&i.Producedmana,
			&i.Promotypes,
			&i.Rarity,
			&i.Rebalancedprintings,
			&i.Relatedcards,
			&i.Securitystamp,
			&i.Setcode,
			&i.Side,
			&i.Signature,
			&i.Skuids,
			&i.Sourceproducts,
			&i.Subsets,
			&i.Subtypes,
			&i.Supertypes,
			&i.Text,
			&i.Toughness,
			&i.Type,
			&i.Types,
			&i.Uuid,
			&i.Variations,
			&i.Watermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCards = `-- name: ListAllCards :many
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards LIMIT ? OFFSET ?
`

type ListAllCardsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListAllCards(ctx context.Context, arg ListAllCardsParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listAllCards, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.Artist,
			&i.Artistids,
			&i.Asciiname,
			&i.Attractionlights,
			&i.Availability,
			&i.Boostertypes,
			&i.Bordercolor,
			&i.Cardparts,
			&i.Coloridentity,
			&i.Colorindicator,
			&i.Colors,
			&i.Defense,
			&i.Dueldeck,
			&i.Edhrecrank,
			&i.Edhrecsaltiness,
			&i.Faceconvertedmanacost,
			&i.Faceflavorname,
			&i.Facemanavalue,
			&i.Facename,
			&i.Faceprintedname,
			&i.Finishes,
			&i.Flavorname,
			&i.Flavortext,
			&i.Frameeffects,
			&i.Frameversion,
			&i.Hand,
			&i.Hasalternativedecklimit,
			&i.Hascontentwarning,
			&i.Isalternative,
			&i.Isfullart,
			&i.Isfunny,
			&i.Isgamechanger,
			&i.Isonlineonly,
			&i.Isoversized,
			&i.Ispromo,
			&i.Isrebalanced,
			&i.Isreprint,
			&i.Isreserved,
			&i.Isstoryspotlight,
			&i.Istextless,
			&i.Istimeshifted,
			&i.Keywords,
			&i.Language,
			&i.Layout,
			&i.Leadershipskills,
			&i.Life,
			&i.Loyalty,
			&i.Manacost,
			&i.Manavalue,
			&i.Name,
			&i.Number,
			&i.Originalprintings,
			&i.Originalreleasedate,
			&i.Originaltext,
			&i.Otherfaceids,
			&i.Power,
			&i.Printedname,
			&i.Printedtext,
			&i.Printedtype,
			&i.Printings,
			&i.Producedmana,
			&i.Promotypes,
			&i.Rarity,
			&i.Rebalancedprintings,
			&i.Relatedcards,
			&i.Securitystamp,
			&i.Setcode,
			&i.Side,
			&i.Signature,
			&i.Skuids,
			&i.Sourceproducts,
			&i.Subsets,
			&i.Subtypes,
			&i.Supertypes,
			&i.Text,
			&i.Toughness,
			&i.Type,
			&i.Types,
			&i.Uuid,
			&i.Variations,
			&i.Watermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCards = `-- name: SearchCards :many
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards 
WHERE 1=1
  AND (? IS NULL OR name LIKE ?)
  AND (? IS NULL OR setcode = ?)
  AND (? IS NULL OR type LIKE ?)
LIMIT ? OFFSET ?
`

type SearchCardsParams struct {
	Column1 interface{}    `json:"column_1"`
	Name    sql.NullString `json:"name"`
	Column3 interface{}    `json:"column_3"`
	Setcode sql.NullString `json:"setcode"`
	Column5 interface{}    `json:"column_5"`
	Type    sql.NullString `json:"type"`
	Limit   int64          `json:"limit"`
	Offset  int64          `json:"offset"`
}

func (q *Queries) SearchCards(ctx context.Context, arg SearchCardsParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, searchCards,
		arg.Column1,
		arg.Name,
		arg.Column3,
		arg.Setcode,
		arg.Column5,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.Artist,
			&i.Artistids,
			&i.Asciiname,
			&i.Attractionlights,
			&i.Availability,
			&i.Boostertypes,
			&i.Bordercolor,
			&i.Cardparts,
			&i.Coloridentity,
			&i.Colorindicator,
			&i.Colors,
			&i.Defense,
			&i.Dueldeck,
			&i.Edhrecrank,
			&i.Edhrecsaltiness,
			&i.Faceconvertedmanacost,
			&i.Faceflavorname,
			&i.Facemanavalue,
			&i.Facename,
			&i.Faceprintedname,
			&i.Finishes,
			&i.Flavorname,
			&i.Flavortext,
			&i.Frameeffects,
			&i.Frameversion,
			&i.Hand,
			&i.Hasalternativedecklimit,
			&i.Hascontentwarning,
			&i.Isalternative,
			&i.Isfullart,
			&i.Isfunny,
			&i.Isgamechanger,
			&i.Isonlineonly,
			&i.Isoversized,
			&i.Ispromo,
			&i.Isrebalanced,
			&i.Isreprint,
			&i.Isreserved,
			&i.Isstoryspotlight,
			&i.Istextless,
			&i.Istimeshifted,
			&i.Keywords,
			&i.Language,
			&i.Layout,
			&i.Leadershipskills,
			&i.Life,
			&i.Loyalty,
			&i.Manacost,
			&i.Manavalue,
			&i.Name,
			&i.Number,
			&i.Originalprintings,
			&i.Originalreleasedate,
			&i.Originaltext,
			&i.Otherfaceids,
			&i.Power,
			&i.Printedname,
			&i.Printedtext,
			&i.Printedtype,
			&i.Printings,
			&i.Producedmana,
			&i.Promotypes,
			&i.Rarity,
			&i.Rebalancedprintings,
			&i.Relatedcards,
			&i.Securitystamp,
			&i.Setcode,
			&i.Side,
			&i.Signature,
			&i.Skuids,
			&i.Sourceproducts,
			&i.Subsets,
			&i.Subtypes,
			&i.Supertypes,
			&i.Text,
			&i.Toughness,
			&i.Type,
			&i.Types,
			&i.Uuid,
			&i.Variations,
			&i.Watermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
