// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Card struct {
	Artist                  sql.NullString  `json:"artist"`
	ArtistIds               sql.NullString  `json:"artistIds"`
	AsciiName               sql.NullString  `json:"asciiName"`
	AttractionLights        sql.NullString  `json:"attractionLights"`
	Availability            sql.NullString  `json:"availability"`
	BoosterTypes            sql.NullString  `json:"boosterTypes"`
	BorderColor             sql.NullString  `json:"borderColor"`
	CardParts               sql.NullString  `json:"cardParts"`
	ColorIdentity           sql.NullString  `json:"colorIdentity"`
	ColorIndicator          sql.NullString  `json:"colorIndicator"`
	Colors                  sql.NullString  `json:"colors"`
	Defense                 sql.NullString  `json:"defense"`
	DuelDeck                sql.NullString  `json:"duelDeck"`
	EdhrecRank              sql.NullInt64   `json:"edhrecRank"`
	EdhrecSaltiness         sql.NullFloat64 `json:"edhrecSaltiness"`
	FaceConvertedManaCost   sql.NullFloat64 `json:"faceConvertedManaCost"`
	FaceFlavorName          sql.NullString  `json:"faceFlavorName"`
	FaceManaValue           sql.NullFloat64 `json:"faceManaValue"`
	FaceName                sql.NullString  `json:"faceName"`
	FacePrintedName         sql.NullString  `json:"facePrintedName"`
	Finishes                sql.NullString  `json:"finishes"`
	FlavorName              sql.NullString  `json:"flavorName"`
	FlavorText              sql.NullString  `json:"flavorText"`
	FrameEffects            sql.NullString  `json:"frameEffects"`
	FrameVersion            sql.NullString  `json:"frameVersion"`
	Hand                    sql.NullString  `json:"hand"`
	HasAlternativeDeckLimit sql.NullBool    `json:"hasAlternativeDeckLimit"`
	HasContentWarning       sql.NullBool    `json:"hasContentWarning"`
	IsAlternative           sql.NullBool    `json:"isAlternative"`
	IsFullArt               sql.NullBool    `json:"isFullArt"`
	IsFunny                 sql.NullBool    `json:"isFunny"`
	IsGameChanger           sql.NullBool    `json:"isGameChanger"`
	IsOnlineOnly            sql.NullBool    `json:"isOnlineOnly"`
	IsOversized             sql.NullBool    `json:"isOversized"`
	IsPromo                 sql.NullBool    `json:"isPromo"`
	IsRebalanced            sql.NullBool    `json:"isRebalanced"`
	IsReprint               sql.NullBool    `json:"isReprint"`
	IsReserved              sql.NullBool    `json:"isReserved"`
	IsStorySpotlight        sql.NullBool    `json:"isStorySpotlight"`
	IsTextless              sql.NullBool    `json:"isTextless"`
	IsTimeshifted           sql.NullBool    `json:"isTimeshifted"`
	Keywords                sql.NullString  `json:"keywords"`
	Language                sql.NullString  `json:"language"`
	Layout                  sql.NullString  `json:"layout"`
	LeadershipSkills        sql.NullString  `json:"leadershipSkills"`
	Life                    sql.NullString  `json:"life"`
	Loyalty                 sql.NullString  `json:"loyalty"`
	ManaCost                sql.NullString  `json:"manaCost"`
	ManaValue               sql.NullFloat64 `json:"manaValue"`
	Name                    sql.NullString  `json:"name"`
	Number                  sql.NullString  `json:"number"`
	OriginalPrintings       sql.NullString  `json:"originalPrintings"`
	OriginalReleaseDate     sql.NullString  `json:"originalReleaseDate"`
	OriginalText            sql.NullString  `json:"originalText"`
	OtherFaceIds            sql.NullString  `json:"otherFaceIds"`
	Power                   sql.NullString  `json:"power"`
	PrintedName             sql.NullString  `json:"printedName"`
	PrintedText             sql.NullString  `json:"printedText"`
	PrintedType             sql.NullString  `json:"printedType"`
	Printings               sql.NullString  `json:"printings"`
	ProducedMana            sql.NullString  `json:"producedMana"`
	PromoTypes              sql.NullString  `json:"promoTypes"`
	Rarity                  sql.NullString  `json:"rarity"`
	RebalancedPrintings     sql.NullString  `json:"rebalancedPrintings"`
	RelatedCards            sql.NullString  `json:"relatedCards"`
	SecurityStamp           sql.NullString  `json:"securityStamp"`
	SetCode                 sql.NullString  `json:"setCode"`
	Side                    sql.NullString  `json:"side"`
	Signature               sql.NullString  `json:"signature"`
	SkuIds                  sql.NullString  `json:"skuIds"`
	SourceProducts          sql.NullString  `json:"sourceProducts"`
	Subsets                 sql.NullString  `json:"subsets"`
	Subtypes                sql.NullString  `json:"subtypes"`
	Supertypes              sql.NullString  `json:"supertypes"`
	Text                    sql.NullString  `json:"text"`
	Toughness               sql.NullString  `json:"toughness"`
	Type                    sql.NullString  `json:"type"`
	Types                   sql.NullString  `json:"types"`
	Uuid                    sql.NullString  `json:"uuid"`
	Variations              sql.NullString  `json:"variations"`
	Watermark               sql.NullString  `json:"watermark"`
}

type CardForeignDatum struct {
	Uuid         sql.NullString `json:"uuid"`
	FaceName     sql.NullString `json:"faceName"`
	SkuIds       sql.NullString `json:"skuIds"`
	FlavorText   sql.NullString `json:"flavorText"`
	Identifiers  sql.NullString `json:"identifiers"`
	Language     sql.NullString `json:"language"`
	MultiverseId sql.NullInt64  `json:"multiverseId"`
	Name         sql.NullString `json:"name"`
	Text         sql.NullString `json:"text"`
	Type         sql.NullString `json:"type"`
}

type CardIdentifier struct {
	Uuid                              sql.NullString `json:"uuid"`
	ScryfallId                        sql.NullString `json:"scryfallId"`
	ScryfallOracleId                  sql.NullString `json:"scryfallOracleId"`
	ScryfallIllustrationId            sql.NullString `json:"scryfallIllustrationId"`
	ScryfallCardBackId                sql.NullString `json:"scryfallCardBackId"`
	McmId                             sql.NullString `json:"mcmId"`
	McmMetaId                         sql.NullString `json:"mcmMetaId"`
	MtgArenaId                        sql.NullString `json:"mtgArenaId"`
	MtgoId                            sql.NullString `json:"mtgoId"`
	MtgoFoilId                        sql.NullString `json:"mtgoFoilId"`
	MultiverseId                      sql.NullString `json:"multiverseId"`
	TcgplayerProductId                sql.NullString `json:"tcgplayerProductId"`
	TcgplayerEtchedProductId          sql.NullString `json:"tcgplayerEtchedProductId"`
	TcgplayerAlternativeFoilProductId sql.NullString `json:"tcgplayerAlternativeFoilProductId"`
	CardKingdomId                     sql.NullString `json:"cardKingdomId"`
	CardKingdomFoilId                 sql.NullString `json:"cardKingdomFoilId"`
	CardKingdomEtchedId               sql.NullString `json:"cardKingdomEtchedId"`
	CardsphereId                      sql.NullString `json:"cardsphereId"`
	CardsphereFoilId                  sql.NullString `json:"cardsphereFoilId"`
	DeckboxId                         sql.NullString `json:"deckboxId"`
	MtgjsonFoilVersionId              sql.NullString `json:"mtgjsonFoilVersionId"`
	MtgjsonNonFoilVersionId           sql.NullString `json:"mtgjsonNonFoilVersionId"`
	MtgjsonV4Id                       sql.NullString `json:"mtgjsonV4Id"`
}

type CardLegality struct {
	Uuid            sql.NullString `json:"uuid"`
	Alchemy         sql.NullString `json:"alchemy"`
	Brawl           sql.NullString `json:"brawl"`
	Commander       sql.NullString `json:"commander"`
	Duel            sql.NullString `json:"duel"`
	Future          sql.NullString `json:"future"`
	Gladiator       sql.NullString `json:"gladiator"`
	Historic        sql.NullString `json:"historic"`
	Legacy          sql.NullString `json:"legacy"`
	Modern          sql.NullString `json:"modern"`
	Oathbreaker     sql.NullString `json:"oathbreaker"`
	Oldschool       sql.NullString `json:"oldschool"`
	Pauper          sql.NullString `json:"pauper"`
	Paupercommander sql.NullString `json:"paupercommander"`
	Penny           sql.NullString `json:"penny"`
	Pioneer         sql.NullString `json:"pioneer"`
	Predh           sql.NullString `json:"predh"`
	Premodern       sql.NullString `json:"premodern"`
	Standard        sql.NullString `json:"standard"`
	Standardbrawl   sql.NullString `json:"standardbrawl"`
	Timeless        sql.NullString `json:"timeless"`
	Vintage         sql.NullString `json:"vintage"`
}

type CardPurchaseUrl struct {
	Uuid                     sql.NullString `json:"uuid"`
	CardKingdom              sql.NullString `json:"cardKingdom"`
	CardKingdomFoil          sql.NullString `json:"cardKingdomFoil"`
	CardKingdomEtched        sql.NullString `json:"cardKingdomEtched"`
	Cardmarket               sql.NullString `json:"cardmarket"`
	CardmarketFoil           sql.NullString `json:"cardmarketFoil"`
	Tcgplayer                sql.NullString `json:"tcgplayer"`
	TcgplayerEtched          sql.NullString `json:"tcgplayerEtched"`
	TcgplayerAlternativeFoil sql.NullString `json:"tcgplayerAlternativeFoil"`
}

type CardRuling struct {
	Uuid sql.NullString `json:"uuid"`
	Date sql.NullTime   `json:"date"`
	Text sql.NullString `json:"text"`
}

type Set struct {
	Code             sql.NullString `json:"code"`
	MtgoCode         sql.NullString `json:"mtgoCode"`
	Name             sql.NullString `json:"name"`
	ReleaseDate      sql.NullString `json:"releaseDate"`
	Type             sql.NullString `json:"type"`
	IsOnlineOnly     sql.NullBool   `json:"isOnlineOnly"`
	IsFoilOnly       sql.NullBool   `json:"isFoilOnly"`
	IsNonFoilOnly    sql.NullBool   `json:"isNonFoilOnly"`
	ParentCode       sql.NullString `json:"parentCode"`
	TotalSetSize     sql.NullInt64  `json:"totalSetSize"`
	BaseSetSize      sql.NullInt64  `json:"baseSetSize"`
	KeyruneCode      sql.NullString `json:"keyruneCode"`
	IsPartialPreview sql.NullBool   `json:"isPartialPreview"`
	IsForeignOnly    sql.NullBool   `json:"isForeignOnly"`
	IsPaperOnly      sql.NullBool   `json:"isPaperOnly"`
	Languages        sql.NullString `json:"languages"`
	TcgplayerGroupId sql.NullInt64  `json:"tcgplayerGroupId"`
	TokenSetCode     sql.NullString `json:"tokenSetCode"`
	McmId            sql.NullInt64  `json:"mcmId"`
	McmName          sql.NullString `json:"mcmName"`
	McmIdExtras      sql.NullInt64  `json:"mcmIdExtras"`
	Block            sql.NullString `json:"block"`
}
