// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetCardByUUID(ctx context.Context, uuid sql.NullString) (Card, error)
	ListCards(ctx context.Context, limit int64) ([]Card, error)
}

var _ Querier = (*Queries)(nil)
