// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sets.sql

package db

import (
	"context"
	"database/sql"
)

const countSets = `-- name: CountSets :one
SELECT COUNT(*) as count FROM sets
`

func (q *Queries) CountSets(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSetByCode = `-- name: GetSetByCode :one
SELECT code, mtgocode, name, releasedate, type, isonlineonly, isfoilonly, isnonfoilonly, parentcode, totalsetsize, basesetsize, keyrunecode, ispartialpreview, isforeignonly, ispaperonly, languages, tcgplayergroupid, tokensetcode, mcmid, mcmname, mcmidextras, block FROM sets WHERE code = ?
`

func (q *Queries) GetSetByCode(ctx context.Context, code sql.NullString) (Set, error) {
	row := q.db.QueryRowContext(ctx, getSetByCode, code)
	var i Set
	err := row.Scan(
		&i.Code,
		&i.Mtgocode,
		&i.Name,
		&i.Releasedate,
		&i.Type,
		&i.Isonlineonly,
		&i.Isfoilonly,
		&i.Isnonfoilonly,
		&i.Parentcode,
		&i.Totalsetsize,
		&i.Basesetsize,
		&i.Keyrunecode,
		&i.Ispartialpreview,
		&i.Isforeignonly,
		&i.Ispaperonly,
		&i.Languages,
		&i.Tcgplayergroupid,
		&i.Tokensetcode,
		&i.Mcmid,
		&i.Mcmname,
		&i.Mcmidextras,
		&i.Block,
	)
	return i, err
}

const getSetByName = `-- name: GetSetByName :many
SELECT code, mtgocode, name, releasedate, type, isonlineonly, isfoilonly, isnonfoilonly, parentcode, totalsetsize, basesetsize, keyrunecode, ispartialpreview, isforeignonly, ispaperonly, languages, tcgplayergroupid, tokensetcode, mcmid, mcmname, mcmidextras, block FROM sets WHERE name LIKE ?
`

func (q *Queries) GetSetByName(ctx context.Context, name sql.NullString) ([]Set, error) {
	rows, err := q.db.QueryContext(ctx, getSetByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Set{}
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.Code,
			&i.Mtgocode,
			&i.Name,
			&i.Releasedate,
			&i.Type,
			&i.Isonlineonly,
			&i.Isfoilonly,
			&i.Isnonfoilonly,
			&i.Parentcode,
			&i.Totalsetsize,
			&i.Basesetsize,
			&i.Keyrunecode,
			&i.Ispartialpreview,
			&i.Isforeignonly,
			&i.Ispaperonly,
			&i.Languages,
			&i.Tcgplayergroupid,
			&i.Tokensetcode,
			&i.Mcmid,
			&i.Mcmname,
			&i.Mcmidextras,
			&i.Block,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSets = `-- name: ListAllSets :many
SELECT code, mtgocode, name, releasedate, type, isonlineonly, isfoilonly, isnonfoilonly, parentcode, totalsetsize, basesetsize, keyrunecode, ispartialpreview, isforeignonly, ispaperonly, languages, tcgplayergroupid, tokensetcode, mcmid, mcmname, mcmidextras, block FROM sets LIMIT ? OFFSET ?
`

type ListAllSetsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListAllSets(ctx context.Context, arg ListAllSetsParams) ([]Set, error) {
	rows, err := q.db.QueryContext(ctx, listAllSets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Set{}
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.Code,
			&i.Mtgocode,
			&i.Name,
			&i.Releasedate,
			&i.Type,
			&i.Isonlineonly,
			&i.Isfoilonly,
			&i.Isnonfoilonly,
			&i.Parentcode,
			&i.Totalsetsize,
			&i.Basesetsize,
			&i.Keyrunecode,
			&i.Ispartialpreview,
			&i.Isforeignonly,
			&i.Ispaperonly,
			&i.Languages,
			&i.Tcgplayergroupid,
			&i.Tokensetcode,
			&i.Mcmid,
			&i.Mcmname,
			&i.Mcmidextras,
			&i.Block,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
