// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: test.sql

package db

import (
	"context"
	"database/sql"
)

const getCardByUUID = `-- name: GetCardByUUID :one
SELECT artist, artistIds, asciiName, attractionLights, availability, boosterTypes, borderColor, cardParts, colorIdentity, colorIndicator, colors, defense, duelDeck, edhrecRank, edhrecSaltiness, faceConvertedManaCost, faceFlavorName, faceManaValue, faceName, facePrintedName, finishes, flavorName, flavorText, frameEffects, frameVersion, hand, hasAlternativeDeckLimit, hasContentWarning, isAlternative, isFullArt, isFunny, isGameChanger, isOnlineOnly, isOversized, isPromo, isRebalanced, isReprint, isReserved, isStorySpotlight, isTextless, isTimeshifted, keywords, language, layout, leadershipSkills, life, loyalty, manaCost, manaValue, name, number, originalPrintings, originalReleaseDate, originalText, otherFaceIds, power, printedName, printedText, printedType, printings, producedMana, promoTypes, rarity, rebalancedPrintings, relatedCards, securityStamp, setCode, side, signature, skuIds, sourceProducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards WHERE uuid = ? LIMIT 1
`

func (q *Queries) GetCardByUUID(ctx context.Context, uuid sql.NullString) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCardByUUID, uuid)
	var i Card
	err := row.Scan(
		&i.Artist,
		&i.ArtistIds,
		&i.AsciiName,
		&i.AttractionLights,
		&i.Availability,
		&i.BoosterTypes,
		&i.BorderColor,
		&i.CardParts,
		&i.ColorIdentity,
		&i.ColorIndicator,
		&i.Colors,
		&i.Defense,
		&i.DuelDeck,
		&i.EdhrecRank,
		&i.EdhrecSaltiness,
		&i.FaceConvertedManaCost,
		&i.FaceFlavorName,
		&i.FaceManaValue,
		&i.FaceName,
		&i.FacePrintedName,
		&i.Finishes,
		&i.FlavorName,
		&i.FlavorText,
		&i.FrameEffects,
		&i.FrameVersion,
		&i.Hand,
		&i.HasAlternativeDeckLimit,
		&i.HasContentWarning,
		&i.IsAlternative,
		&i.IsFullArt,
		&i.IsFunny,
		&i.IsGameChanger,
		&i.IsOnlineOnly,
		&i.IsOversized,
		&i.IsPromo,
		&i.IsRebalanced,
		&i.IsReprint,
		&i.IsReserved,
		&i.IsStorySpotlight,
		&i.IsTextless,
		&i.IsTimeshifted,
		&i.Keywords,
		&i.Language,
		&i.Layout,
		&i.LeadershipSkills,
		&i.Life,
		&i.Loyalty,
		&i.ManaCost,
		&i.ManaValue,
		&i.Name,
		&i.Number,
		&i.OriginalPrintings,
		&i.OriginalReleaseDate,
		&i.OriginalText,
		&i.OtherFaceIds,
		&i.Power,
		&i.PrintedName,
		&i.PrintedText,
		&i.PrintedType,
		&i.Printings,
		&i.ProducedMana,
		&i.PromoTypes,
		&i.Rarity,
		&i.RebalancedPrintings,
		&i.RelatedCards,
		&i.SecurityStamp,
		&i.SetCode,
		&i.Side,
		&i.Signature,
		&i.SkuIds,
		&i.SourceProducts,
		&i.Subsets,
		&i.Subtypes,
		&i.Supertypes,
		&i.Text,
		&i.Toughness,
		&i.Type,
		&i.Types,
		&i.Uuid,
		&i.Variations,
		&i.Watermark,
	)
	return i, err
}

const listCards = `-- name: ListCards :many
SELECT artist, artistIds, asciiName, attractionLights, availability, boosterTypes, borderColor, cardParts, colorIdentity, colorIndicator, colors, defense, duelDeck, edhrecRank, edhrecSaltiness, faceConvertedManaCost, faceFlavorName, faceManaValue, faceName, facePrintedName, finishes, flavorName, flavorText, frameEffects, frameVersion, hand, hasAlternativeDeckLimit, hasContentWarning, isAlternative, isFullArt, isFunny, isGameChanger, isOnlineOnly, isOversized, isPromo, isRebalanced, isReprint, isReserved, isStorySpotlight, isTextless, isTimeshifted, keywords, language, layout, leadershipSkills, life, loyalty, manaCost, manaValue, name, number, originalPrintings, originalReleaseDate, originalText, otherFaceIds, power, printedName, printedText, printedType, printings, producedMana, promoTypes, rarity, rebalancedPrintings, relatedCards, securityStamp, setCode, side, signature, skuIds, sourceProducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards LIMIT ?
`

func (q *Queries) ListCards(ctx context.Context, limit int64) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listCards, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.Artist,
			&i.ArtistIds,
			&i.AsciiName,
			&i.AttractionLights,
			&i.Availability,
			&i.BoosterTypes,
			&i.BorderColor,
			&i.CardParts,
			&i.ColorIdentity,
			&i.ColorIndicator,
			&i.Colors,
			&i.Defense,
			&i.DuelDeck,
			&i.EdhrecRank,
			&i.EdhrecSaltiness,
			&i.FaceConvertedManaCost,
			&i.FaceFlavorName,
			&i.FaceManaValue,
			&i.FaceName,
			&i.FacePrintedName,
			&i.Finishes,
			&i.FlavorName,
			&i.FlavorText,
			&i.FrameEffects,
			&i.FrameVersion,
			&i.Hand,
			&i.HasAlternativeDeckLimit,
			&i.HasContentWarning,
			&i.IsAlternative,
			&i.IsFullArt,
			&i.IsFunny,
			&i.IsGameChanger,
			&i.IsOnlineOnly,
			&i.IsOversized,
			&i.IsPromo,
			&i.IsRebalanced,
			&i.IsReprint,
			&i.IsReserved,
			&i.IsStorySpotlight,
			&i.IsTextless,
			&i.IsTimeshifted,
			&i.Keywords,
			&i.Language,
			&i.Layout,
			&i.LeadershipSkills,
			&i.Life,
			&i.Loyalty,
			&i.ManaCost,
			&i.ManaValue,
			&i.Name,
			&i.Number,
			&i.OriginalPrintings,
			&i.OriginalReleaseDate,
			&i.OriginalText,
			&i.OtherFaceIds,
			&i.Power,
			&i.PrintedName,
			&i.PrintedText,
			&i.PrintedType,
			&i.Printings,
			&i.ProducedMana,
			&i.PromoTypes,
			&i.Rarity,
			&i.RebalancedPrintings,
			&i.RelatedCards,
			&i.SecurityStamp,
			&i.SetCode,
			&i.Side,
			&i.Signature,
			&i.SkuIds,
			&i.SourceProducts,
			&i.Subsets,
			&i.Subtypes,
			&i.Supertypes,
			&i.Text,
			&i.Toughness,
			&i.Type,
			&i.Types,
			&i.Uuid,
			&i.Variations,
			&i.Watermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
