// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: test.sql

package db

import (
	"context"
	"database/sql"
)

const getCardByUUID = `-- name: GetCardByUUID :one
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards WHERE uuid = ? LIMIT 1
`

func (q *Queries) GetCardByUUID(ctx context.Context, uuid sql.NullString) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCardByUUID, uuid)
	var i Card
	err := row.Scan(
		&i.Artist,
		&i.Artistids,
		&i.Asciiname,
		&i.Attractionlights,
		&i.Availability,
		&i.Boostertypes,
		&i.Bordercolor,
		&i.Cardparts,
		&i.Coloridentity,
		&i.Colorindicator,
		&i.Colors,
		&i.Defense,
		&i.Dueldeck,
		&i.Edhrecrank,
		&i.Edhrecsaltiness,
		&i.Faceconvertedmanacost,
		&i.Faceflavorname,
		&i.Facemanavalue,
		&i.Facename,
		&i.Faceprintedname,
		&i.Finishes,
		&i.Flavorname,
		&i.Flavortext,
		&i.Frameeffects,
		&i.Frameversion,
		&i.Hand,
		&i.Hasalternativedecklimit,
		&i.Hascontentwarning,
		&i.Isalternative,
		&i.Isfullart,
		&i.Isfunny,
		&i.Isgamechanger,
		&i.Isonlineonly,
		&i.Isoversized,
		&i.Ispromo,
		&i.Isrebalanced,
		&i.Isreprint,
		&i.Isreserved,
		&i.Isstoryspotlight,
		&i.Istextless,
		&i.Istimeshifted,
		&i.Keywords,
		&i.Language,
		&i.Layout,
		&i.Leadershipskills,
		&i.Life,
		&i.Loyalty,
		&i.Manacost,
		&i.Manavalue,
		&i.Name,
		&i.Number,
		&i.Originalprintings,
		&i.Originalreleasedate,
		&i.Originaltext,
		&i.Otherfaceids,
		&i.Power,
		&i.Printedname,
		&i.Printedtext,
		&i.Printedtype,
		&i.Printings,
		&i.Producedmana,
		&i.Promotypes,
		&i.Rarity,
		&i.Rebalancedprintings,
		&i.Relatedcards,
		&i.Securitystamp,
		&i.Setcode,
		&i.Side,
		&i.Signature,
		&i.Skuids,
		&i.Sourceproducts,
		&i.Subsets,
		&i.Subtypes,
		&i.Supertypes,
		&i.Text,
		&i.Toughness,
		&i.Type,
		&i.Types,
		&i.Uuid,
		&i.Variations,
		&i.Watermark,
	)
	return i, err
}

const listCards = `-- name: ListCards :many
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards LIMIT ?
`

func (q *Queries) ListCards(ctx context.Context, limit int64) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listCards, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.Artist,
			&i.Artistids,
			&i.Asciiname,
			&i.Attractionlights,
			&i.Availability,
			&i.Boostertypes,
			&i.Bordercolor,
			&i.Cardparts,
			&i.Coloridentity,
			&i.Colorindicator,
			&i.Colors,
			&i.Defense,
			&i.Dueldeck,
			&i.Edhrecrank,
			&i.Edhrecsaltiness,
			&i.Faceconvertedmanacost,
			&i.Faceflavorname,
			&i.Facemanavalue,
			&i.Facename,
			&i.Faceprintedname,
			&i.Finishes,
			&i.Flavorname,
			&i.Flavortext,
			&i.Frameeffects,
			&i.Frameversion,
			&i.Hand,
			&i.Hasalternativedecklimit,
			&i.Hascontentwarning,
			&i.Isalternative,
			&i.Isfullart,
			&i.Isfunny,
			&i.Isgamechanger,
			&i.Isonlineonly,
			&i.Isoversized,
			&i.Ispromo,
			&i.Isrebalanced,
			&i.Isreprint,
			&i.Isreserved,
			&i.Isstoryspotlight,
			&i.Istextless,
			&i.Istimeshifted,
			&i.Keywords,
			&i.Language,
			&i.Layout,
			&i.Leadershipskills,
			&i.Life,
			&i.Loyalty,
			&i.Manacost,
			&i.Manavalue,
			&i.Name,
			&i.Number,
			&i.Originalprintings,
			&i.Originalreleasedate,
			&i.Originaltext,
			&i.Otherfaceids,
			&i.Power,
			&i.Printedname,
			&i.Printedtext,
			&i.Printedtype,
			&i.Printings,
			&i.Producedmana,
			&i.Promotypes,
			&i.Rarity,
			&i.Rebalancedprintings,
			&i.Relatedcards,
			&i.Securitystamp,
			&i.Setcode,
			&i.Side,
			&i.Signature,
			&i.Skuids,
			&i.Sourceproducts,
			&i.Subsets,
			&i.Subtypes,
			&i.Supertypes,
			&i.Text,
			&i.Toughness,
			&i.Type,
			&i.Types,
			&i.Uuid,
			&i.Variations,
			&i.Watermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
