syntax = "proto3";

package packets;

option go_package = "/pkg/packets";

// General

message PingMessage {
  uint64 timestamp = 1;
}

message ChatMessage {
  string msg = 1;
}

message IdMessage {
  uint64 id = 1;
}

// Authentication

message LoginRequestMessage {
  string username = 1;
  string password = 2;
}

message RegisterRequestMessage {
  string username = 1;
  string password = 2;
}

message OkResponseMessage {}

message DenyResponseMessage {
  string reason = 2;
}

// Lobby messages

message LobbyPlayerData {
  uint64 client_id = 1;
  string username = 2;
  bool is_ready = 3;
}

message LobbyData {
  uint64 id = 1;
  string name = 2;
  int32 current_players = 3;
  int32 max_players = 4;
}

// List

message ListLobbiesRequest {
  // Pagination
  int32 page = 1;
  int32 page_size = 2;

  // Filters
  string name = 3;
  string format = 4;
  int32 state = 5;
}

message ListLobbiesResponse {
  int32 count = 1;
  repeated LobbyData lobbies = 2;
}

// Create

message CreateLobbyRequest {
  string name = 1;
  string format = 2;
  int32 max_players = 3;
  bool is_private = 4;
  optional string password = 5;
}

message CreateLobbyResponse {}

// Join

message JoinLobbyRequest {
  uint64 lobby_id = 1;
  optional string password = 2;
}

message JoinedLobbyResponse {
  uint64 lobby_id = 1;
  string lobby_name = 2;
  string host_username = 3;
  repeated LobbyPlayerData players = 4;
}

// Leave

message LeaveLobbyRequest {}

message LeftLobbyResponse {
  uint64 client_id = 1;
}

// Ready

message ReadyLobbyRequest {
  bool is_ready = 1;
}

message UpdatePlayerLobbyStatus {
  LobbyPlayerData updated_player = 1;
}

message StartGameRequest {}

message LobbyGameStartedResponse {}

// Entry
message Packet {
  uint64 sender_id = 1;
  oneof msg {
    // General messages
    PingMessage ping = 2;
    ChatMessage chat = 3;
    IdMessage id = 4;

    // Authentication messages
    LoginRequestMessage login_request = 5;
    RegisterRequestMessage register_request = 6;
    OkResponseMessage ok_response = 7;
    DenyResponseMessage deny_response = 8;

    // Lobby messages
    ListLobbiesRequest list_lobbies_request = 9;
    ListLobbiesResponse list_lobbies_response = 10;

    CreateLobbyRequest create_lobby_request = 11;
    CreateLobbyResponse create_lobby_response = 12;

    JoinLobbyRequest join_lobby_request = 13;
    JoinedLobbyResponse joined_lobby_response = 14;

    LeaveLobbyRequest leave_lobby_request = 15;
    LeftLobbyResponse left_lobby_response = 16;

    ReadyLobbyRequest ready_lobby_request = 17;
    UpdatePlayerLobbyStatus update_player_lobby_status = 18;

    StartGameRequest start_game_request = 19;
    LobbyGameStartedResponse lobby_game_started_response = 20;

    // Game messages
  }
}
