// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: packets.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingMessage) Reset() {
	*x = PingMessage{}
	mi := &file_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMessage) ProtoMessage() {}

func (x *PingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMessage.ProtoReflect.Descriptor instead.
func (*PingMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *PingMessage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type IdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdMessage) Reset() {
	*x = IdMessage{}
	mi := &file_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMessage) ProtoMessage() {}

func (x *IdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMessage.ProtoReflect.Descriptor instead.
func (*IdMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

func (x *IdMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoginRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequestMessage) Reset() {
	*x = LoginRequestMessage{}
	mi := &file_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestMessage) ProtoMessage() {}

func (x *LoginRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestMessage.ProtoReflect.Descriptor instead.
func (*LoginRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequestMessage) Reset() {
	*x = RegisterRequestMessage{}
	mi := &file_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequestMessage) ProtoMessage() {}

func (x *RegisterRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequestMessage.ProtoReflect.Descriptor instead.
func (*RegisterRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type OkResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OkResponseMessage) Reset() {
	*x = OkResponseMessage{}
	mi := &file_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OkResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkResponseMessage) ProtoMessage() {}

func (x *OkResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkResponseMessage.ProtoReflect.Descriptor instead.
func (*OkResponseMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{5}
}

type DenyResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyResponseMessage) Reset() {
	*x = DenyResponseMessage{}
	mi := &file_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyResponseMessage) ProtoMessage() {}

func (x *DenyResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyResponseMessage.ProtoReflect.Descriptor instead.
func (*DenyResponseMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{6}
}

func (x *DenyResponseMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LobbyPlayerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	IsReady       bool                   `protobuf:"varint,3,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyPlayerData) Reset() {
	*x = LobbyPlayerData{}
	mi := &file_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyPlayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyPlayerData) ProtoMessage() {}

func (x *LobbyPlayerData) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyPlayerData.ProtoReflect.Descriptor instead.
func (*LobbyPlayerData) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{7}
}

func (x *LobbyPlayerData) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *LobbyPlayerData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LobbyPlayerData) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type LobbyData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CurrentPlayers int32                  `protobuf:"varint,3,opt,name=current_players,json=currentPlayers,proto3" json:"current_players,omitempty"`
	MaxPlayers     int32                  `protobuf:"varint,4,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LobbyData) Reset() {
	*x = LobbyData{}
	mi := &file_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyData) ProtoMessage() {}

func (x *LobbyData) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyData.ProtoReflect.Descriptor instead.
func (*LobbyData) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{8}
}

func (x *LobbyData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LobbyData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LobbyData) GetCurrentPlayers() int32 {
	if x != nil {
		return x.CurrentPlayers
	}
	return 0
}

func (x *LobbyData) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

type ListLobbiesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination
	Page     int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Filters
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Format        string `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	State         int32  `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLobbiesRequest) Reset() {
	*x = ListLobbiesRequest{}
	mi := &file_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLobbiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLobbiesRequest) ProtoMessage() {}

func (x *ListLobbiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLobbiesRequest.ProtoReflect.Descriptor instead.
func (*ListLobbiesRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{9}
}

func (x *ListLobbiesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLobbiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLobbiesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListLobbiesRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ListLobbiesRequest) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type ListLobbiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Lobbies       []*LobbyData           `protobuf:"bytes,2,rep,name=lobbies,proto3" json:"lobbies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLobbiesResponse) Reset() {
	*x = ListLobbiesResponse{}
	mi := &file_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLobbiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLobbiesResponse) ProtoMessage() {}

func (x *ListLobbiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLobbiesResponse.ProtoReflect.Descriptor instead.
func (*ListLobbiesResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{10}
}

func (x *ListLobbiesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListLobbiesResponse) GetLobbies() []*LobbyData {
	if x != nil {
		return x.Lobbies
	}
	return nil
}

type CreateLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,3,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,4,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	Password      *string                `protobuf:"bytes,5,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyRequest) Reset() {
	*x = CreateLobbyRequest{}
	mi := &file_packets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyRequest) ProtoMessage() {}

func (x *CreateLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyRequest.ProtoReflect.Descriptor instead.
func (*CreateLobbyRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{11}
}

func (x *CreateLobbyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLobbyRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *CreateLobbyRequest) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *CreateLobbyRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *CreateLobbyRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type CreateLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyResponse) Reset() {
	*x = CreateLobbyResponse{}
	mi := &file_packets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyResponse) ProtoMessage() {}

func (x *CreateLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyResponse.ProtoReflect.Descriptor instead.
func (*CreateLobbyResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{12}
}

type JoinLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       uint64                 `protobuf:"varint,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLobbyRequest) Reset() {
	*x = JoinLobbyRequest{}
	mi := &file_packets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyRequest) ProtoMessage() {}

func (x *JoinLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyRequest.ProtoReflect.Descriptor instead.
func (*JoinLobbyRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{13}
}

func (x *JoinLobbyRequest) GetLobbyId() uint64 {
	if x != nil {
		return x.LobbyId
	}
	return 0
}

func (x *JoinLobbyRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type JoinedLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       uint64                 `protobuf:"varint,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	LobbyName     string                 `protobuf:"bytes,2,opt,name=lobby_name,json=lobbyName,proto3" json:"lobby_name,omitempty"`
	HostUsername  string                 `protobuf:"bytes,3,opt,name=host_username,json=hostUsername,proto3" json:"host_username,omitempty"`
	Players       []*LobbyPlayerData     `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinedLobbyResponse) Reset() {
	*x = JoinedLobbyResponse{}
	mi := &file_packets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinedLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinedLobbyResponse) ProtoMessage() {}

func (x *JoinedLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinedLobbyResponse.ProtoReflect.Descriptor instead.
func (*JoinedLobbyResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{14}
}

func (x *JoinedLobbyResponse) GetLobbyId() uint64 {
	if x != nil {
		return x.LobbyId
	}
	return 0
}

func (x *JoinedLobbyResponse) GetLobbyName() string {
	if x != nil {
		return x.LobbyName
	}
	return ""
}

func (x *JoinedLobbyResponse) GetHostUsername() string {
	if x != nil {
		return x.HostUsername
	}
	return ""
}

func (x *JoinedLobbyResponse) GetPlayers() []*LobbyPlayerData {
	if x != nil {
		return x.Players
	}
	return nil
}

type PlayerJoinedLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *LobbyPlayerData       `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoinedLobbyResponse) Reset() {
	*x = PlayerJoinedLobbyResponse{}
	mi := &file_packets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoinedLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoinedLobbyResponse) ProtoMessage() {}

func (x *PlayerJoinedLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoinedLobbyResponse.ProtoReflect.Descriptor instead.
func (*PlayerJoinedLobbyResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{15}
}

func (x *PlayerJoinedLobbyResponse) GetPlayer() *LobbyPlayerData {
	if x != nil {
		return x.Player
	}
	return nil
}

// Entry
type Packet struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SenderId uint64                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Packet_Ping
	//	*Packet_Chat
	//	*Packet_Id
	//	*Packet_LoginRequest
	//	*Packet_RegisterRequest
	//	*Packet_OkResponse
	//	*Packet_DenyResponse
	//	*Packet_ListLobbiesRequest
	//	*Packet_ListLobbiesResponse
	//	*Packet_CreateLobbyRequest
	//	*Packet_CreateLobbyResponse
	//	*Packet_JoinLobbyRequest
	//	*Packet_JoinedLobbyResponse
	//	*Packet_PlayerJoinedLobbyResponse
	Msg           isPacket_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_packets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{16}
}

func (x *Packet) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Packet) GetMsg() isPacket_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Packet) GetPing() *PingMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Packet) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Packet) GetId() *IdMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *Packet) GetLoginRequest() *LoginRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LoginRequest); ok {
			return x.LoginRequest
		}
	}
	return nil
}

func (x *Packet) GetRegisterRequest() *RegisterRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *Packet) GetOkResponse() *OkResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_OkResponse); ok {
			return x.OkResponse
		}
	}
	return nil
}

func (x *Packet) GetDenyResponse() *DenyResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_DenyResponse); ok {
			return x.DenyResponse
		}
	}
	return nil
}

func (x *Packet) GetListLobbiesRequest() *ListLobbiesRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_ListLobbiesRequest); ok {
			return x.ListLobbiesRequest
		}
	}
	return nil
}

func (x *Packet) GetListLobbiesResponse() *ListLobbiesResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_ListLobbiesResponse); ok {
			return x.ListLobbiesResponse
		}
	}
	return nil
}

func (x *Packet) GetCreateLobbyRequest() *CreateLobbyRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_CreateLobbyRequest); ok {
			return x.CreateLobbyRequest
		}
	}
	return nil
}

func (x *Packet) GetCreateLobbyResponse() *CreateLobbyResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_CreateLobbyResponse); ok {
			return x.CreateLobbyResponse
		}
	}
	return nil
}

func (x *Packet) GetJoinLobbyRequest() *JoinLobbyRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_JoinLobbyRequest); ok {
			return x.JoinLobbyRequest
		}
	}
	return nil
}

func (x *Packet) GetJoinedLobbyResponse() *JoinedLobbyResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_JoinedLobbyResponse); ok {
			return x.JoinedLobbyResponse
		}
	}
	return nil
}

func (x *Packet) GetPlayerJoinedLobbyResponse() *PlayerJoinedLobbyResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerJoinedLobbyResponse); ok {
			return x.PlayerJoinedLobbyResponse
		}
	}
	return nil
}

type isPacket_Msg interface {
	isPacket_Msg()
}

type Packet_Ping struct {
	// General messages
	Ping *PingMessage `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type Packet_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,3,opt,name=chat,proto3,oneof"`
}

type Packet_Id struct {
	Id *IdMessage `protobuf:"bytes,4,opt,name=id,proto3,oneof"`
}

type Packet_LoginRequest struct {
	// Authentication messages
	LoginRequest *LoginRequestMessage `protobuf:"bytes,5,opt,name=login_request,json=loginRequest,proto3,oneof"`
}

type Packet_RegisterRequest struct {
	RegisterRequest *RegisterRequestMessage `protobuf:"bytes,6,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type Packet_OkResponse struct {
	OkResponse *OkResponseMessage `protobuf:"bytes,7,opt,name=ok_response,json=okResponse,proto3,oneof"`
}

type Packet_DenyResponse struct {
	DenyResponse *DenyResponseMessage `protobuf:"bytes,8,opt,name=deny_response,json=denyResponse,proto3,oneof"`
}

type Packet_ListLobbiesRequest struct {
	// Lobby messages
	ListLobbiesRequest *ListLobbiesRequest `protobuf:"bytes,9,opt,name=list_lobbies_request,json=listLobbiesRequest,proto3,oneof"`
}

type Packet_ListLobbiesResponse struct {
	ListLobbiesResponse *ListLobbiesResponse `protobuf:"bytes,10,opt,name=list_lobbies_response,json=listLobbiesResponse,proto3,oneof"`
}

type Packet_CreateLobbyRequest struct {
	CreateLobbyRequest *CreateLobbyRequest `protobuf:"bytes,11,opt,name=create_lobby_request,json=createLobbyRequest,proto3,oneof"`
}

type Packet_CreateLobbyResponse struct {
	CreateLobbyResponse *CreateLobbyResponse `protobuf:"bytes,12,opt,name=create_lobby_response,json=createLobbyResponse,proto3,oneof"`
}

type Packet_JoinLobbyRequest struct {
	JoinLobbyRequest *JoinLobbyRequest `protobuf:"bytes,13,opt,name=join_lobby_request,json=joinLobbyRequest,proto3,oneof"`
}

type Packet_JoinedLobbyResponse struct {
	JoinedLobbyResponse *JoinedLobbyResponse `protobuf:"bytes,14,opt,name=joined_lobby_response,json=joinedLobbyResponse,proto3,oneof"`
}

type Packet_PlayerJoinedLobbyResponse struct {
	PlayerJoinedLobbyResponse *PlayerJoinedLobbyResponse `protobuf:"bytes,15,opt,name=player_joined_lobby_response,json=playerJoinedLobbyResponse,proto3,oneof"`
}

func (*Packet_Ping) isPacket_Msg() {}

func (*Packet_Chat) isPacket_Msg() {}

func (*Packet_Id) isPacket_Msg() {}

func (*Packet_LoginRequest) isPacket_Msg() {}

func (*Packet_RegisterRequest) isPacket_Msg() {}

func (*Packet_OkResponse) isPacket_Msg() {}

func (*Packet_DenyResponse) isPacket_Msg() {}

func (*Packet_ListLobbiesRequest) isPacket_Msg() {}

func (*Packet_ListLobbiesResponse) isPacket_Msg() {}

func (*Packet_CreateLobbyRequest) isPacket_Msg() {}

func (*Packet_CreateLobbyResponse) isPacket_Msg() {}

func (*Packet_JoinLobbyRequest) isPacket_Msg() {}

func (*Packet_JoinedLobbyResponse) isPacket_Msg() {}

func (*Packet_PlayerJoinedLobbyResponse) isPacket_Msg() {}

var File_packets_proto protoreflect.FileDescriptor

const file_packets_proto_rawDesc = "" +
	"\n" +
	"\rpackets.proto\x12\apackets\"+\n" +
	"\vPingMessage\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\"\x1f\n" +
	"\vChatMessage\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x1b\n" +
	"\tIdMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"M\n" +
	"\x13LoginRequestMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"P\n" +
	"\x16RegisterRequestMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x13\n" +
	"\x11OkResponseMessage\"-\n" +
	"\x13DenyResponseMessage\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"e\n" +
	"\x0fLobbyPlayerData\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x19\n" +
	"\bis_ready\x18\x03 \x01(\bR\aisReady\"y\n" +
	"\tLobbyData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fcurrent_players\x18\x03 \x01(\x05R\x0ecurrentPlayers\x12\x1f\n" +
	"\vmax_players\x18\x04 \x01(\x05R\n" +
	"maxPlayers\"\x87\x01\n" +
	"\x12ListLobbiesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x14\n" +
	"\x05state\x18\x05 \x01(\x05R\x05state\"Y\n" +
	"\x13ListLobbiesResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12,\n" +
	"\alobbies\x18\x02 \x03(\v2\x12.packets.LobbyDataR\alobbies\"\xae\x01\n" +
	"\x12CreateLobbyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1f\n" +
	"\vmax_players\x18\x03 \x01(\x05R\n" +
	"maxPlayers\x12\x1d\n" +
	"\n" +
	"is_private\x18\x04 \x01(\bR\tisPrivate\x12\x1f\n" +
	"\bpassword\x18\x05 \x01(\tH\x00R\bpassword\x88\x01\x01B\v\n" +
	"\t_password\"\x15\n" +
	"\x13CreateLobbyResponse\"[\n" +
	"\x10JoinLobbyRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\x04R\alobbyId\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tH\x00R\bpassword\x88\x01\x01B\v\n" +
	"\t_password\"\xa8\x01\n" +
	"\x13JoinedLobbyResponse\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\x04R\alobbyId\x12\x1d\n" +
	"\n" +
	"lobby_name\x18\x02 \x01(\tR\tlobbyName\x12#\n" +
	"\rhost_username\x18\x03 \x01(\tR\fhostUsername\x122\n" +
	"\aplayers\x18\x04 \x03(\v2\x18.packets.LobbyPlayerDataR\aplayers\"M\n" +
	"\x19PlayerJoinedLobbyResponse\x120\n" +
	"\x06player\x18\x01 \x01(\v2\x18.packets.LobbyPlayerDataR\x06player\"\x91\b\n" +
	"\x06Packet\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x04R\bsenderId\x12*\n" +
	"\x04ping\x18\x02 \x01(\v2\x14.packets.PingMessageH\x00R\x04ping\x12*\n" +
	"\x04chat\x18\x03 \x01(\v2\x14.packets.ChatMessageH\x00R\x04chat\x12$\n" +
	"\x02id\x18\x04 \x01(\v2\x12.packets.IdMessageH\x00R\x02id\x12C\n" +
	"\rlogin_request\x18\x05 \x01(\v2\x1c.packets.LoginRequestMessageH\x00R\floginRequest\x12L\n" +
	"\x10register_request\x18\x06 \x01(\v2\x1f.packets.RegisterRequestMessageH\x00R\x0fregisterRequest\x12=\n" +
	"\vok_response\x18\a \x01(\v2\x1a.packets.OkResponseMessageH\x00R\n" +
	"okResponse\x12C\n" +
	"\rdeny_response\x18\b \x01(\v2\x1c.packets.DenyResponseMessageH\x00R\fdenyResponse\x12O\n" +
	"\x14list_lobbies_request\x18\t \x01(\v2\x1b.packets.ListLobbiesRequestH\x00R\x12listLobbiesRequest\x12R\n" +
	"\x15list_lobbies_response\x18\n" +
	" \x01(\v2\x1c.packets.ListLobbiesResponseH\x00R\x13listLobbiesResponse\x12O\n" +
	"\x14create_lobby_request\x18\v \x01(\v2\x1b.packets.CreateLobbyRequestH\x00R\x12createLobbyRequest\x12R\n" +
	"\x15create_lobby_response\x18\f \x01(\v2\x1c.packets.CreateLobbyResponseH\x00R\x13createLobbyResponse\x12I\n" +
	"\x12join_lobby_request\x18\r \x01(\v2\x19.packets.JoinLobbyRequestH\x00R\x10joinLobbyRequest\x12R\n" +
	"\x15joined_lobby_response\x18\x0e \x01(\v2\x1c.packets.JoinedLobbyResponseH\x00R\x13joinedLobbyResponse\x12e\n" +
	"\x1cplayer_joined_lobby_response\x18\x0f \x01(\v2\".packets.PlayerJoinedLobbyResponseH\x00R\x19playerJoinedLobbyResponseB\x05\n" +
	"\x03msgB\x0eZ\f/pkg/packetsb\x06proto3"

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData []byte
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)))
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_packets_proto_goTypes = []any{
	(*PingMessage)(nil),               // 0: packets.PingMessage
	(*ChatMessage)(nil),               // 1: packets.ChatMessage
	(*IdMessage)(nil),                 // 2: packets.IdMessage
	(*LoginRequestMessage)(nil),       // 3: packets.LoginRequestMessage
	(*RegisterRequestMessage)(nil),    // 4: packets.RegisterRequestMessage
	(*OkResponseMessage)(nil),         // 5: packets.OkResponseMessage
	(*DenyResponseMessage)(nil),       // 6: packets.DenyResponseMessage
	(*LobbyPlayerData)(nil),           // 7: packets.LobbyPlayerData
	(*LobbyData)(nil),                 // 8: packets.LobbyData
	(*ListLobbiesRequest)(nil),        // 9: packets.ListLobbiesRequest
	(*ListLobbiesResponse)(nil),       // 10: packets.ListLobbiesResponse
	(*CreateLobbyRequest)(nil),        // 11: packets.CreateLobbyRequest
	(*CreateLobbyResponse)(nil),       // 12: packets.CreateLobbyResponse
	(*JoinLobbyRequest)(nil),          // 13: packets.JoinLobbyRequest
	(*JoinedLobbyResponse)(nil),       // 14: packets.JoinedLobbyResponse
	(*PlayerJoinedLobbyResponse)(nil), // 15: packets.PlayerJoinedLobbyResponse
	(*Packet)(nil),                    // 16: packets.Packet
}
var file_packets_proto_depIdxs = []int32{
	8,  // 0: packets.ListLobbiesResponse.lobbies:type_name -> packets.LobbyData
	7,  // 1: packets.JoinedLobbyResponse.players:type_name -> packets.LobbyPlayerData
	7,  // 2: packets.PlayerJoinedLobbyResponse.player:type_name -> packets.LobbyPlayerData
	0,  // 3: packets.Packet.ping:type_name -> packets.PingMessage
	1,  // 4: packets.Packet.chat:type_name -> packets.ChatMessage
	2,  // 5: packets.Packet.id:type_name -> packets.IdMessage
	3,  // 6: packets.Packet.login_request:type_name -> packets.LoginRequestMessage
	4,  // 7: packets.Packet.register_request:type_name -> packets.RegisterRequestMessage
	5,  // 8: packets.Packet.ok_response:type_name -> packets.OkResponseMessage
	6,  // 9: packets.Packet.deny_response:type_name -> packets.DenyResponseMessage
	9,  // 10: packets.Packet.list_lobbies_request:type_name -> packets.ListLobbiesRequest
	10, // 11: packets.Packet.list_lobbies_response:type_name -> packets.ListLobbiesResponse
	11, // 12: packets.Packet.create_lobby_request:type_name -> packets.CreateLobbyRequest
	12, // 13: packets.Packet.create_lobby_response:type_name -> packets.CreateLobbyResponse
	13, // 14: packets.Packet.join_lobby_request:type_name -> packets.JoinLobbyRequest
	14, // 15: packets.Packet.joined_lobby_response:type_name -> packets.JoinedLobbyResponse
	15, // 16: packets.Packet.player_joined_lobby_response:type_name -> packets.PlayerJoinedLobbyResponse
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	file_packets_proto_msgTypes[11].OneofWrappers = []any{}
	file_packets_proto_msgTypes[13].OneofWrappers = []any{}
	file_packets_proto_msgTypes[16].OneofWrappers = []any{
		(*Packet_Ping)(nil),
		(*Packet_Chat)(nil),
		(*Packet_Id)(nil),
		(*Packet_LoginRequest)(nil),
		(*Packet_RegisterRequest)(nil),
		(*Packet_OkResponse)(nil),
		(*Packet_DenyResponse)(nil),
		(*Packet_ListLobbiesRequest)(nil),
		(*Packet_ListLobbiesResponse)(nil),
		(*Packet_CreateLobbyRequest)(nil),
		(*Packet_CreateLobbyResponse)(nil),
		(*Packet_JoinLobbyRequest)(nil),
		(*Packet_JoinedLobbyResponse)(nil),
		(*Packet_PlayerJoinedLobbyResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
