// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: packets.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingMessage) Reset() {
	*x = PingMessage{}
	mi := &file_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMessage) ProtoMessage() {}

func (x *PingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMessage.ProtoReflect.Descriptor instead.
func (*PingMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *PingMessage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type IdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdMessage) Reset() {
	*x = IdMessage{}
	mi := &file_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMessage) ProtoMessage() {}

func (x *IdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMessage.ProtoReflect.Descriptor instead.
func (*IdMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

func (x *IdMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoginRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequestMessage) Reset() {
	*x = LoginRequestMessage{}
	mi := &file_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestMessage) ProtoMessage() {}

func (x *LoginRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestMessage.ProtoReflect.Descriptor instead.
func (*LoginRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequestMessage) Reset() {
	*x = RegisterRequestMessage{}
	mi := &file_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequestMessage) ProtoMessage() {}

func (x *RegisterRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequestMessage.ProtoReflect.Descriptor instead.
func (*RegisterRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type OkResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OkResponseMessage) Reset() {
	*x = OkResponseMessage{}
	mi := &file_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OkResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkResponseMessage) ProtoMessage() {}

func (x *OkResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkResponseMessage.ProtoReflect.Descriptor instead.
func (*OkResponseMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{5}
}

type DenyResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyResponseMessage) Reset() {
	*x = DenyResponseMessage{}
	mi := &file_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyResponseMessage) ProtoMessage() {}

func (x *DenyResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyResponseMessage.ProtoReflect.Descriptor instead.
func (*DenyResponseMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{6}
}

func (x *DenyResponseMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Lobby messages
type LobbyCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,3,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,4,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	Password      *string                `protobuf:"bytes,5,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyCreateRequest) Reset() {
	*x = LobbyCreateRequest{}
	mi := &file_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyCreateRequest) ProtoMessage() {}

func (x *LobbyCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyCreateRequest.ProtoReflect.Descriptor instead.
func (*LobbyCreateRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{7}
}

func (x *LobbyCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LobbyCreateRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *LobbyCreateRequest) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *LobbyCreateRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *LobbyCreateRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type LobbyJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       uint64                 `protobuf:"varint,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyJoinRequest) Reset() {
	*x = LobbyJoinRequest{}
	mi := &file_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyJoinRequest) ProtoMessage() {}

func (x *LobbyJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyJoinRequest.ProtoReflect.Descriptor instead.
func (*LobbyJoinRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{8}
}

func (x *LobbyJoinRequest) GetLobbyId() uint64 {
	if x != nil {
		return x.LobbyId
	}
	return 0
}

func (x *LobbyJoinRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type LobbyLeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyLeaveRequest) Reset() {
	*x = LobbyLeaveRequest{}
	mi := &file_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyLeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyLeaveRequest) ProtoMessage() {}

func (x *LobbyLeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyLeaveRequest.ProtoReflect.Descriptor instead.
func (*LobbyLeaveRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{9}
}

type LobbyReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyReadyRequest) Reset() {
	*x = LobbyReadyRequest{}
	mi := &file_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyReadyRequest) ProtoMessage() {}

func (x *LobbyReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyReadyRequest.ProtoReflect.Descriptor instead.
func (*LobbyReadyRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{10}
}

func (x *LobbyReadyRequest) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type LobbyStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyStartRequest) Reset() {
	*x = LobbyStartRequest{}
	mi := &file_packets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyStartRequest) ProtoMessage() {}

func (x *LobbyStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyStartRequest.ProtoReflect.Descriptor instead.
func (*LobbyStartRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{11}
}

type LobbyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyListRequest) Reset() {
	*x = LobbyListRequest{}
	mi := &file_packets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyListRequest) ProtoMessage() {}

func (x *LobbyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyListRequest.ProtoReflect.Descriptor instead.
func (*LobbyListRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{12}
}

type LobbyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobbies       []*LobbyInfo           `protobuf:"bytes,1,rep,name=lobbies,proto3" json:"lobbies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyListResponse) Reset() {
	*x = LobbyListResponse{}
	mi := &file_packets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyListResponse) ProtoMessage() {}

func (x *LobbyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyListResponse.ProtoReflect.Descriptor instead.
func (*LobbyListResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{13}
}

func (x *LobbyListResponse) GetLobbies() []*LobbyInfo {
	if x != nil {
		return x.Lobbies
	}
	return nil
}

type LobbyInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Format         string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	CurrentPlayers int32                  `protobuf:"varint,4,opt,name=current_players,json=currentPlayers,proto3" json:"current_players,omitempty"`
	MaxPlayers     int32                  `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	HostUsername   string                 `protobuf:"bytes,6,opt,name=host_username,json=hostUsername,proto3" json:"host_username,omitempty"`
	IsPrivate      bool                   `protobuf:"varint,7,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LobbyInfo) Reset() {
	*x = LobbyInfo{}
	mi := &file_packets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyInfo) ProtoMessage() {}

func (x *LobbyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyInfo.ProtoReflect.Descriptor instead.
func (*LobbyInfo) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{14}
}

func (x *LobbyInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LobbyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LobbyInfo) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *LobbyInfo) GetCurrentPlayers() int32 {
	if x != nil {
		return x.CurrentPlayers
	}
	return 0
}

func (x *LobbyInfo) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *LobbyInfo) GetHostUsername() string {
	if x != nil {
		return x.HostUsername
	}
	return ""
}

func (x *LobbyInfo) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

type LobbyJoinedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       uint64                 `protobuf:"varint,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	LobbyName     string                 `protobuf:"bytes,2,opt,name=lobby_name,json=lobbyName,proto3" json:"lobby_name,omitempty"`
	HostUsername  string                 `protobuf:"bytes,3,opt,name=host_username,json=hostUsername,proto3" json:"host_username,omitempty"`
	Players       []*LobbyPlayer         `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyJoinedResponse) Reset() {
	*x = LobbyJoinedResponse{}
	mi := &file_packets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyJoinedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyJoinedResponse) ProtoMessage() {}

func (x *LobbyJoinedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyJoinedResponse.ProtoReflect.Descriptor instead.
func (*LobbyJoinedResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{15}
}

func (x *LobbyJoinedResponse) GetLobbyId() uint64 {
	if x != nil {
		return x.LobbyId
	}
	return 0
}

func (x *LobbyJoinedResponse) GetLobbyName() string {
	if x != nil {
		return x.LobbyName
	}
	return ""
}

func (x *LobbyJoinedResponse) GetHostUsername() string {
	if x != nil {
		return x.HostUsername
	}
	return ""
}

func (x *LobbyJoinedResponse) GetPlayers() []*LobbyPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

type LobbyPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Ready         bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyPlayer) Reset() {
	*x = LobbyPlayer{}
	mi := &file_packets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyPlayer) ProtoMessage() {}

func (x *LobbyPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyPlayer.ProtoReflect.Descriptor instead.
func (*LobbyPlayer) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{16}
}

func (x *LobbyPlayer) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *LobbyPlayer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LobbyPlayer) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type LobbyPlayerJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *LobbyPlayer           `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyPlayerJoined) Reset() {
	*x = LobbyPlayerJoined{}
	mi := &file_packets_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyPlayerJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyPlayerJoined) ProtoMessage() {}

func (x *LobbyPlayerJoined) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyPlayerJoined.ProtoReflect.Descriptor instead.
func (*LobbyPlayerJoined) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{17}
}

func (x *LobbyPlayerJoined) GetPlayer() *LobbyPlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

type LobbyPlayerLeft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyPlayerLeft) Reset() {
	*x = LobbyPlayerLeft{}
	mi := &file_packets_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyPlayerLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyPlayerLeft) ProtoMessage() {}

func (x *LobbyPlayerLeft) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyPlayerLeft.ProtoReflect.Descriptor instead.
func (*LobbyPlayerLeft) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{18}
}

func (x *LobbyPlayerLeft) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type LobbyPlayerReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyPlayerReady) Reset() {
	*x = LobbyPlayerReady{}
	mi := &file_packets_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyPlayerReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyPlayerReady) ProtoMessage() {}

func (x *LobbyPlayerReady) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyPlayerReady.ProtoReflect.Descriptor instead.
func (*LobbyPlayerReady) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{19}
}

func (x *LobbyPlayerReady) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *LobbyPlayerReady) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type LobbyGameStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyGameStart) Reset() {
	*x = LobbyGameStart{}
	mi := &file_packets_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyGameStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyGameStart) ProtoMessage() {}

func (x *LobbyGameStart) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyGameStart.ProtoReflect.Descriptor instead.
func (*LobbyGameStart) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{20}
}

type Packet struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SenderId uint64                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Packet_Ping
	//	*Packet_Chat
	//	*Packet_Id
	//	*Packet_LoginRequest
	//	*Packet_RegisterRequest
	//	*Packet_OkResponse
	//	*Packet_DenyResponse
	//	*Packet_LobbyCreateRequest
	//	*Packet_LobbyJoinRequest
	//	*Packet_LobbyListRequest
	//	*Packet_LobbyListResponse
	//	*Packet_LobbyJoinedResponse
	//	*Packet_LobbyLeaveRequest
	//	*Packet_LobbyReadyRequest
	//	*Packet_LobbyStartRequest
	//	*Packet_LobbyPlayerJoined
	//	*Packet_LobbyPlayerLeft
	//	*Packet_LobbyPlayerReady
	//	*Packet_LobbyGameStart
	Msg           isPacket_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_packets_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{21}
}

func (x *Packet) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Packet) GetMsg() isPacket_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Packet) GetPing() *PingMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Packet) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Packet) GetId() *IdMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *Packet) GetLoginRequest() *LoginRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LoginRequest); ok {
			return x.LoginRequest
		}
	}
	return nil
}

func (x *Packet) GetRegisterRequest() *RegisterRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *Packet) GetOkResponse() *OkResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_OkResponse); ok {
			return x.OkResponse
		}
	}
	return nil
}

func (x *Packet) GetDenyResponse() *DenyResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_DenyResponse); ok {
			return x.DenyResponse
		}
	}
	return nil
}

func (x *Packet) GetLobbyCreateRequest() *LobbyCreateRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LobbyCreateRequest); ok {
			return x.LobbyCreateRequest
		}
	}
	return nil
}

func (x *Packet) GetLobbyJoinRequest() *LobbyJoinRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LobbyJoinRequest); ok {
			return x.LobbyJoinRequest
		}
	}
	return nil
}

func (x *Packet) GetLobbyListRequest() *LobbyListRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LobbyListRequest); ok {
			return x.LobbyListRequest
		}
	}
	return nil
}

func (x *Packet) GetLobbyListResponse() *LobbyListResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LobbyListResponse); ok {
			return x.LobbyListResponse
		}
	}
	return nil
}

func (x *Packet) GetLobbyJoinedResponse() *LobbyJoinedResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LobbyJoinedResponse); ok {
			return x.LobbyJoinedResponse
		}
	}
	return nil
}

func (x *Packet) GetLobbyLeaveRequest() *LobbyLeaveRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LobbyLeaveRequest); ok {
			return x.LobbyLeaveRequest
		}
	}
	return nil
}

func (x *Packet) GetLobbyReadyRequest() *LobbyReadyRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LobbyReadyRequest); ok {
			return x.LobbyReadyRequest
		}
	}
	return nil
}

func (x *Packet) GetLobbyStartRequest() *LobbyStartRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LobbyStartRequest); ok {
			return x.LobbyStartRequest
		}
	}
	return nil
}

func (x *Packet) GetLobbyPlayerJoined() *LobbyPlayerJoined {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LobbyPlayerJoined); ok {
			return x.LobbyPlayerJoined
		}
	}
	return nil
}

func (x *Packet) GetLobbyPlayerLeft() *LobbyPlayerLeft {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LobbyPlayerLeft); ok {
			return x.LobbyPlayerLeft
		}
	}
	return nil
}

func (x *Packet) GetLobbyPlayerReady() *LobbyPlayerReady {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LobbyPlayerReady); ok {
			return x.LobbyPlayerReady
		}
	}
	return nil
}

func (x *Packet) GetLobbyGameStart() *LobbyGameStart {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LobbyGameStart); ok {
			return x.LobbyGameStart
		}
	}
	return nil
}

type isPacket_Msg interface {
	isPacket_Msg()
}

type Packet_Ping struct {
	// General messages
	Ping *PingMessage `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type Packet_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,3,opt,name=chat,proto3,oneof"`
}

type Packet_Id struct {
	Id *IdMessage `protobuf:"bytes,4,opt,name=id,proto3,oneof"`
}

type Packet_LoginRequest struct {
	// Authentication messages
	LoginRequest *LoginRequestMessage `protobuf:"bytes,5,opt,name=login_request,json=loginRequest,proto3,oneof"`
}

type Packet_RegisterRequest struct {
	RegisterRequest *RegisterRequestMessage `protobuf:"bytes,6,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type Packet_OkResponse struct {
	OkResponse *OkResponseMessage `protobuf:"bytes,7,opt,name=ok_response,json=okResponse,proto3,oneof"`
}

type Packet_DenyResponse struct {
	DenyResponse *DenyResponseMessage `protobuf:"bytes,8,opt,name=deny_response,json=denyResponse,proto3,oneof"`
}

type Packet_LobbyCreateRequest struct {
	// Lobby messages
	LobbyCreateRequest *LobbyCreateRequest `protobuf:"bytes,9,opt,name=lobby_create_request,json=lobbyCreateRequest,proto3,oneof"`
}

type Packet_LobbyJoinRequest struct {
	LobbyJoinRequest *LobbyJoinRequest `protobuf:"bytes,10,opt,name=lobby_join_request,json=lobbyJoinRequest,proto3,oneof"`
}

type Packet_LobbyListRequest struct {
	LobbyListRequest *LobbyListRequest `protobuf:"bytes,14,opt,name=lobby_list_request,json=lobbyListRequest,proto3,oneof"`
}

type Packet_LobbyListResponse struct {
	LobbyListResponse *LobbyListResponse `protobuf:"bytes,15,opt,name=lobby_list_response,json=lobbyListResponse,proto3,oneof"`
}

type Packet_LobbyJoinedResponse struct {
	LobbyJoinedResponse *LobbyJoinedResponse `protobuf:"bytes,16,opt,name=lobby_joined_response,json=lobbyJoinedResponse,proto3,oneof"`
}

type Packet_LobbyLeaveRequest struct {
	LobbyLeaveRequest *LobbyLeaveRequest `protobuf:"bytes,11,opt,name=lobby_leave_request,json=lobbyLeaveRequest,proto3,oneof"`
}

type Packet_LobbyReadyRequest struct {
	LobbyReadyRequest *LobbyReadyRequest `protobuf:"bytes,12,opt,name=lobby_ready_request,json=lobbyReadyRequest,proto3,oneof"`
}

type Packet_LobbyStartRequest struct {
	LobbyStartRequest *LobbyStartRequest `protobuf:"bytes,13,opt,name=lobby_start_request,json=lobbyStartRequest,proto3,oneof"`
}

type Packet_LobbyPlayerJoined struct {
	LobbyPlayerJoined *LobbyPlayerJoined `protobuf:"bytes,17,opt,name=lobby_player_joined,json=lobbyPlayerJoined,proto3,oneof"` // Player joined the lobby
}

type Packet_LobbyPlayerLeft struct {
	LobbyPlayerLeft *LobbyPlayerLeft `protobuf:"bytes,18,opt,name=lobby_player_left,json=lobbyPlayerLeft,proto3,oneof"` // Player left the lobby
}

type Packet_LobbyPlayerReady struct {
	LobbyPlayerReady *LobbyPlayerReady `protobuf:"bytes,19,opt,name=lobby_player_ready,json=lobbyPlayerReady,proto3,oneof"` // Player is ready/unready
}

type Packet_LobbyGameStart struct {
	LobbyGameStart *LobbyGameStart `protobuf:"bytes,20,opt,name=lobby_game_start,json=lobbyGameStart,proto3,oneof"` // Game has started
}

func (*Packet_Ping) isPacket_Msg() {}

func (*Packet_Chat) isPacket_Msg() {}

func (*Packet_Id) isPacket_Msg() {}

func (*Packet_LoginRequest) isPacket_Msg() {}

func (*Packet_RegisterRequest) isPacket_Msg() {}

func (*Packet_OkResponse) isPacket_Msg() {}

func (*Packet_DenyResponse) isPacket_Msg() {}

func (*Packet_LobbyCreateRequest) isPacket_Msg() {}

func (*Packet_LobbyJoinRequest) isPacket_Msg() {}

func (*Packet_LobbyListRequest) isPacket_Msg() {}

func (*Packet_LobbyListResponse) isPacket_Msg() {}

func (*Packet_LobbyJoinedResponse) isPacket_Msg() {}

func (*Packet_LobbyLeaveRequest) isPacket_Msg() {}

func (*Packet_LobbyReadyRequest) isPacket_Msg() {}

func (*Packet_LobbyStartRequest) isPacket_Msg() {}

func (*Packet_LobbyPlayerJoined) isPacket_Msg() {}

func (*Packet_LobbyPlayerLeft) isPacket_Msg() {}

func (*Packet_LobbyPlayerReady) isPacket_Msg() {}

func (*Packet_LobbyGameStart) isPacket_Msg() {}

var File_packets_proto protoreflect.FileDescriptor

const file_packets_proto_rawDesc = "" +
	"\n" +
	"\rpackets.proto\x12\apackets\"+\n" +
	"\vPingMessage\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\"\x1f\n" +
	"\vChatMessage\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x1b\n" +
	"\tIdMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"M\n" +
	"\x13LoginRequestMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"P\n" +
	"\x16RegisterRequestMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x13\n" +
	"\x11OkResponseMessage\"-\n" +
	"\x13DenyResponseMessage\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xae\x01\n" +
	"\x12LobbyCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1f\n" +
	"\vmax_players\x18\x03 \x01(\x05R\n" +
	"maxPlayers\x12\x1d\n" +
	"\n" +
	"is_private\x18\x04 \x01(\bR\tisPrivate\x12\x1f\n" +
	"\bpassword\x18\x05 \x01(\tH\x00R\bpassword\x88\x01\x01B\v\n" +
	"\t_password\"[\n" +
	"\x10LobbyJoinRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\x04R\alobbyId\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tH\x00R\bpassword\x88\x01\x01B\v\n" +
	"\t_password\"\x13\n" +
	"\x11LobbyLeaveRequest\")\n" +
	"\x11LobbyReadyRequest\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\"\x13\n" +
	"\x11LobbyStartRequest\"\x12\n" +
	"\x10LobbyListRequest\"A\n" +
	"\x11LobbyListResponse\x12,\n" +
	"\alobbies\x18\x01 \x03(\v2\x12.packets.LobbyInfoR\alobbies\"\xd5\x01\n" +
	"\tLobbyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12'\n" +
	"\x0fcurrent_players\x18\x04 \x01(\x05R\x0ecurrentPlayers\x12\x1f\n" +
	"\vmax_players\x18\x05 \x01(\x05R\n" +
	"maxPlayers\x12#\n" +
	"\rhost_username\x18\x06 \x01(\tR\fhostUsername\x12\x1d\n" +
	"\n" +
	"is_private\x18\a \x01(\bR\tisPrivate\"\xa4\x01\n" +
	"\x13LobbyJoinedResponse\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\x04R\alobbyId\x12\x1d\n" +
	"\n" +
	"lobby_name\x18\x02 \x01(\tR\tlobbyName\x12#\n" +
	"\rhost_username\x18\x03 \x01(\tR\fhostUsername\x12.\n" +
	"\aplayers\x18\x04 \x03(\v2\x14.packets.LobbyPlayerR\aplayers\"\\\n" +
	"\vLobbyPlayer\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\"A\n" +
	"\x11LobbyPlayerJoined\x12,\n" +
	"\x06player\x18\x01 \x01(\v2\x14.packets.LobbyPlayerR\x06player\".\n" +
	"\x0fLobbyPlayerLeft\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\"E\n" +
	"\x10LobbyPlayerReady\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\"\x10\n" +
	"\x0eLobbyGameStart\"\xda\n" +
	"\n" +
	"\x06Packet\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x04R\bsenderId\x12*\n" +
	"\x04ping\x18\x02 \x01(\v2\x14.packets.PingMessageH\x00R\x04ping\x12*\n" +
	"\x04chat\x18\x03 \x01(\v2\x14.packets.ChatMessageH\x00R\x04chat\x12$\n" +
	"\x02id\x18\x04 \x01(\v2\x12.packets.IdMessageH\x00R\x02id\x12C\n" +
	"\rlogin_request\x18\x05 \x01(\v2\x1c.packets.LoginRequestMessageH\x00R\floginRequest\x12L\n" +
	"\x10register_request\x18\x06 \x01(\v2\x1f.packets.RegisterRequestMessageH\x00R\x0fregisterRequest\x12=\n" +
	"\vok_response\x18\a \x01(\v2\x1a.packets.OkResponseMessageH\x00R\n" +
	"okResponse\x12C\n" +
	"\rdeny_response\x18\b \x01(\v2\x1c.packets.DenyResponseMessageH\x00R\fdenyResponse\x12O\n" +
	"\x14lobby_create_request\x18\t \x01(\v2\x1b.packets.LobbyCreateRequestH\x00R\x12lobbyCreateRequest\x12I\n" +
	"\x12lobby_join_request\x18\n" +
	" \x01(\v2\x19.packets.LobbyJoinRequestH\x00R\x10lobbyJoinRequest\x12I\n" +
	"\x12lobby_list_request\x18\x0e \x01(\v2\x19.packets.LobbyListRequestH\x00R\x10lobbyListRequest\x12L\n" +
	"\x13lobby_list_response\x18\x0f \x01(\v2\x1a.packets.LobbyListResponseH\x00R\x11lobbyListResponse\x12R\n" +
	"\x15lobby_joined_response\x18\x10 \x01(\v2\x1c.packets.LobbyJoinedResponseH\x00R\x13lobbyJoinedResponse\x12L\n" +
	"\x13lobby_leave_request\x18\v \x01(\v2\x1a.packets.LobbyLeaveRequestH\x00R\x11lobbyLeaveRequest\x12L\n" +
	"\x13lobby_ready_request\x18\f \x01(\v2\x1a.packets.LobbyReadyRequestH\x00R\x11lobbyReadyRequest\x12L\n" +
	"\x13lobby_start_request\x18\r \x01(\v2\x1a.packets.LobbyStartRequestH\x00R\x11lobbyStartRequest\x12L\n" +
	"\x13lobby_player_joined\x18\x11 \x01(\v2\x1a.packets.LobbyPlayerJoinedH\x00R\x11lobbyPlayerJoined\x12F\n" +
	"\x11lobby_player_left\x18\x12 \x01(\v2\x18.packets.LobbyPlayerLeftH\x00R\x0flobbyPlayerLeft\x12I\n" +
	"\x12lobby_player_ready\x18\x13 \x01(\v2\x19.packets.LobbyPlayerReadyH\x00R\x10lobbyPlayerReady\x12C\n" +
	"\x10lobby_game_start\x18\x14 \x01(\v2\x17.packets.LobbyGameStartH\x00R\x0elobbyGameStartB\x05\n" +
	"\x03msgB\x0eZ\f/pkg/packetsb\x06proto3"

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData []byte
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)))
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_packets_proto_goTypes = []any{
	(*PingMessage)(nil),            // 0: packets.PingMessage
	(*ChatMessage)(nil),            // 1: packets.ChatMessage
	(*IdMessage)(nil),              // 2: packets.IdMessage
	(*LoginRequestMessage)(nil),    // 3: packets.LoginRequestMessage
	(*RegisterRequestMessage)(nil), // 4: packets.RegisterRequestMessage
	(*OkResponseMessage)(nil),      // 5: packets.OkResponseMessage
	(*DenyResponseMessage)(nil),    // 6: packets.DenyResponseMessage
	(*LobbyCreateRequest)(nil),     // 7: packets.LobbyCreateRequest
	(*LobbyJoinRequest)(nil),       // 8: packets.LobbyJoinRequest
	(*LobbyLeaveRequest)(nil),      // 9: packets.LobbyLeaveRequest
	(*LobbyReadyRequest)(nil),      // 10: packets.LobbyReadyRequest
	(*LobbyStartRequest)(nil),      // 11: packets.LobbyStartRequest
	(*LobbyListRequest)(nil),       // 12: packets.LobbyListRequest
	(*LobbyListResponse)(nil),      // 13: packets.LobbyListResponse
	(*LobbyInfo)(nil),              // 14: packets.LobbyInfo
	(*LobbyJoinedResponse)(nil),    // 15: packets.LobbyJoinedResponse
	(*LobbyPlayer)(nil),            // 16: packets.LobbyPlayer
	(*LobbyPlayerJoined)(nil),      // 17: packets.LobbyPlayerJoined
	(*LobbyPlayerLeft)(nil),        // 18: packets.LobbyPlayerLeft
	(*LobbyPlayerReady)(nil),       // 19: packets.LobbyPlayerReady
	(*LobbyGameStart)(nil),         // 20: packets.LobbyGameStart
	(*Packet)(nil),                 // 21: packets.Packet
}
var file_packets_proto_depIdxs = []int32{
	14, // 0: packets.LobbyListResponse.lobbies:type_name -> packets.LobbyInfo
	16, // 1: packets.LobbyJoinedResponse.players:type_name -> packets.LobbyPlayer
	16, // 2: packets.LobbyPlayerJoined.player:type_name -> packets.LobbyPlayer
	0,  // 3: packets.Packet.ping:type_name -> packets.PingMessage
	1,  // 4: packets.Packet.chat:type_name -> packets.ChatMessage
	2,  // 5: packets.Packet.id:type_name -> packets.IdMessage
	3,  // 6: packets.Packet.login_request:type_name -> packets.LoginRequestMessage
	4,  // 7: packets.Packet.register_request:type_name -> packets.RegisterRequestMessage
	5,  // 8: packets.Packet.ok_response:type_name -> packets.OkResponseMessage
	6,  // 9: packets.Packet.deny_response:type_name -> packets.DenyResponseMessage
	7,  // 10: packets.Packet.lobby_create_request:type_name -> packets.LobbyCreateRequest
	8,  // 11: packets.Packet.lobby_join_request:type_name -> packets.LobbyJoinRequest
	12, // 12: packets.Packet.lobby_list_request:type_name -> packets.LobbyListRequest
	13, // 13: packets.Packet.lobby_list_response:type_name -> packets.LobbyListResponse
	15, // 14: packets.Packet.lobby_joined_response:type_name -> packets.LobbyJoinedResponse
	9,  // 15: packets.Packet.lobby_leave_request:type_name -> packets.LobbyLeaveRequest
	10, // 16: packets.Packet.lobby_ready_request:type_name -> packets.LobbyReadyRequest
	11, // 17: packets.Packet.lobby_start_request:type_name -> packets.LobbyStartRequest
	17, // 18: packets.Packet.lobby_player_joined:type_name -> packets.LobbyPlayerJoined
	18, // 19: packets.Packet.lobby_player_left:type_name -> packets.LobbyPlayerLeft
	19, // 20: packets.Packet.lobby_player_ready:type_name -> packets.LobbyPlayerReady
	20, // 21: packets.Packet.lobby_game_start:type_name -> packets.LobbyGameStart
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	file_packets_proto_msgTypes[7].OneofWrappers = []any{}
	file_packets_proto_msgTypes[8].OneofWrappers = []any{}
	file_packets_proto_msgTypes[21].OneofWrappers = []any{
		(*Packet_Ping)(nil),
		(*Packet_Chat)(nil),
		(*Packet_Id)(nil),
		(*Packet_LoginRequest)(nil),
		(*Packet_RegisterRequest)(nil),
		(*Packet_OkResponse)(nil),
		(*Packet_DenyResponse)(nil),
		(*Packet_LobbyCreateRequest)(nil),
		(*Packet_LobbyJoinRequest)(nil),
		(*Packet_LobbyListRequest)(nil),
		(*Packet_LobbyListResponse)(nil),
		(*Packet_LobbyJoinedResponse)(nil),
		(*Packet_LobbyLeaveRequest)(nil),
		(*Packet_LobbyReadyRequest)(nil),
		(*Packet_LobbyStartRequest)(nil),
		(*Packet_LobbyPlayerJoined)(nil),
		(*Packet_LobbyPlayerLeft)(nil),
		(*Packet_LobbyPlayerReady)(nil),
		(*Packet_LobbyGameStart)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
