// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package cards

import (
	"context"
	"database/sql"
)

const countCards = `-- name: CountCards :one
;

SELECT COUNT(*) as count FROM cards
`

func (q *Queries) CountCards(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCards)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCardByName = `-- name: GetCardByName :many
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards WHERE name LIKE ?
`

func (q *Queries) GetCardByName(ctx context.Context, name sql.NullString) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getCardByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.Artist,
			&i.Artistids,
			&i.Asciiname,
			&i.Attractionlights,
			&i.Availability,
			&i.Boostertypes,
			&i.Bordercolor,
			&i.Cardparts,
			&i.Coloridentity,
			&i.Colorindicator,
			&i.Colors,
			&i.Defense,
			&i.Dueldeck,
			&i.Edhrecrank,
			&i.Edhrecsaltiness,
			&i.Faceconvertedmanacost,
			&i.Faceflavorname,
			&i.Facemanavalue,
			&i.Facename,
			&i.Faceprintedname,
			&i.Finishes,
			&i.Flavorname,
			&i.Flavortext,
			&i.Frameeffects,
			&i.Frameversion,
			&i.Hand,
			&i.Hasalternativedecklimit,
			&i.Hascontentwarning,
			&i.Isalternative,
			&i.Isfullart,
			&i.Isfunny,
			&i.Isgamechanger,
			&i.Isonlineonly,
			&i.Isoversized,
			&i.Ispromo,
			&i.Isrebalanced,
			&i.Isreprint,
			&i.Isreserved,
			&i.Isstoryspotlight,
			&i.Istextless,
			&i.Istimeshifted,
			&i.Keywords,
			&i.Language,
			&i.Layout,
			&i.Leadershipskills,
			&i.Life,
			&i.Loyalty,
			&i.Manacost,
			&i.Manavalue,
			&i.Name,
			&i.Number,
			&i.Originalprintings,
			&i.Originalreleasedate,
			&i.Originaltext,
			&i.Otherfaceids,
			&i.Power,
			&i.Printedname,
			&i.Printedtext,
			&i.Printedtype,
			&i.Printings,
			&i.Producedmana,
			&i.Promotypes,
			&i.Rarity,
			&i.Rebalancedprintings,
			&i.Relatedcards,
			&i.Securitystamp,
			&i.Setcode,
			&i.Side,
			&i.Signature,
			&i.Skuids,
			&i.Sourceproducts,
			&i.Subsets,
			&i.Subtypes,
			&i.Supertypes,
			&i.Text,
			&i.Toughness,
			&i.Type,
			&i.Types,
			&i.Uuid,
			&i.Variations,
			&i.Watermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardByUuid = `-- name: GetCardByUuid :one
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards WHERE uuid = ?
`

func (q *Queries) GetCardByUuid(ctx context.Context, uuid sql.NullString) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCardByUuid, uuid)
	var i Card
	err := row.Scan(
		&i.Artist,
		&i.Artistids,
		&i.Asciiname,
		&i.Attractionlights,
		&i.Availability,
		&i.Boostertypes,
		&i.Bordercolor,
		&i.Cardparts,
		&i.Coloridentity,
		&i.Colorindicator,
		&i.Colors,
		&i.Defense,
		&i.Dueldeck,
		&i.Edhrecrank,
		&i.Edhrecsaltiness,
		&i.Faceconvertedmanacost,
		&i.Faceflavorname,
		&i.Facemanavalue,
		&i.Facename,
		&i.Faceprintedname,
		&i.Finishes,
		&i.Flavorname,
		&i.Flavortext,
		&i.Frameeffects,
		&i.Frameversion,
		&i.Hand,
		&i.Hasalternativedecklimit,
		&i.Hascontentwarning,
		&i.Isalternative,
		&i.Isfullart,
		&i.Isfunny,
		&i.Isgamechanger,
		&i.Isonlineonly,
		&i.Isoversized,
		&i.Ispromo,
		&i.Isrebalanced,
		&i.Isreprint,
		&i.Isreserved,
		&i.Isstoryspotlight,
		&i.Istextless,
		&i.Istimeshifted,
		&i.Keywords,
		&i.Language,
		&i.Layout,
		&i.Leadershipskills,
		&i.Life,
		&i.Loyalty,
		&i.Manacost,
		&i.Manavalue,
		&i.Name,
		&i.Number,
		&i.Originalprintings,
		&i.Originalreleasedate,
		&i.Originaltext,
		&i.Otherfaceids,
		&i.Power,
		&i.Printedname,
		&i.Printedtext,
		&i.Printedtype,
		&i.Printings,
		&i.Producedmana,
		&i.Promotypes,
		&i.Rarity,
		&i.Rebalancedprintings,
		&i.Relatedcards,
		&i.Securitystamp,
		&i.Setcode,
		&i.Side,
		&i.Signature,
		&i.Skuids,
		&i.Sourceproducts,
		&i.Subsets,
		&i.Subtypes,
		&i.Supertypes,
		&i.Text,
		&i.Toughness,
		&i.Type,
		&i.Types,
		&i.Uuid,
		&i.Variations,
		&i.Watermark,
	)
	return i, err
}

const getCardsByColor = `-- name: GetCardsByColor :many
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards WHERE colors LIKE ? LIMIT ? OFFSET ?
`

type GetCardsByColorParams struct {
	Colors sql.NullString
	Limit  int64
	Offset int64
}

func (q *Queries) GetCardsByColor(ctx context.Context, arg GetCardsByColorParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getCardsByColor, arg.Colors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.Artist,
			&i.Artistids,
			&i.Asciiname,
			&i.Attractionlights,
			&i.Availability,
			&i.Boostertypes,
			&i.Bordercolor,
			&i.Cardparts,
			&i.Coloridentity,
			&i.Colorindicator,
			&i.Colors,
			&i.Defense,
			&i.Dueldeck,
			&i.Edhrecrank,
			&i.Edhrecsaltiness,
			&i.Faceconvertedmanacost,
			&i.Faceflavorname,
			&i.Facemanavalue,
			&i.Facename,
			&i.Faceprintedname,
			&i.Finishes,
			&i.Flavorname,
			&i.Flavortext,
			&i.Frameeffects,
			&i.Frameversion,
			&i.Hand,
			&i.Hasalternativedecklimit,
			&i.Hascontentwarning,
			&i.Isalternative,
			&i.Isfullart,
			&i.Isfunny,
			&i.Isgamechanger,
			&i.Isonlineonly,
			&i.Isoversized,
			&i.Ispromo,
			&i.Isrebalanced,
			&i.Isreprint,
			&i.Isreserved,
			&i.Isstoryspotlight,
			&i.Istextless,
			&i.Istimeshifted,
			&i.Keywords,
			&i.Language,
			&i.Layout,
			&i.Leadershipskills,
			&i.Life,
			&i.Loyalty,
			&i.Manacost,
			&i.Manavalue,
			&i.Name,
			&i.Number,
			&i.Originalprintings,
			&i.Originalreleasedate,
			&i.Originaltext,
			&i.Otherfaceids,
			&i.Power,
			&i.Printedname,
			&i.Printedtext,
			&i.Printedtype,
			&i.Printings,
			&i.Producedmana,
			&i.Promotypes,
			&i.Rarity,
			&i.Rebalancedprintings,
			&i.Relatedcards,
			&i.Securitystamp,
			&i.Setcode,
			&i.Side,
			&i.Signature,
			&i.Skuids,
			&i.Sourceproducts,
			&i.Subsets,
			&i.Subtypes,
			&i.Supertypes,
			&i.Text,
			&i.Toughness,
			&i.Type,
			&i.Types,
			&i.Uuid,
			&i.Variations,
			&i.Watermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardsByManaValue = `-- name: GetCardsByManaValue :many
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards WHERE manavalue = ? LIMIT ? OFFSET ?
`

type GetCardsByManaValueParams struct {
	Manavalue sql.NullFloat64
	Limit     int64
	Offset    int64
}

func (q *Queries) GetCardsByManaValue(ctx context.Context, arg GetCardsByManaValueParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getCardsByManaValue, arg.Manavalue, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.Artist,
			&i.Artistids,
			&i.Asciiname,
			&i.Attractionlights,
			&i.Availability,
			&i.Boostertypes,
			&i.Bordercolor,
			&i.Cardparts,
			&i.Coloridentity,
			&i.Colorindicator,
			&i.Colors,
			&i.Defense,
			&i.Dueldeck,
			&i.Edhrecrank,
			&i.Edhrecsaltiness,
			&i.Faceconvertedmanacost,
			&i.Faceflavorname,
			&i.Facemanavalue,
			&i.Facename,
			&i.Faceprintedname,
			&i.Finishes,
			&i.Flavorname,
			&i.Flavortext,
			&i.Frameeffects,
			&i.Frameversion,
			&i.Hand,
			&i.Hasalternativedecklimit,
			&i.Hascontentwarning,
			&i.Isalternative,
			&i.Isfullart,
			&i.Isfunny,
			&i.Isgamechanger,
			&i.Isonlineonly,
			&i.Isoversized,
			&i.Ispromo,
			&i.Isrebalanced,
			&i.Isreprint,
			&i.Isreserved,
			&i.Isstoryspotlight,
			&i.Istextless,
			&i.Istimeshifted,
			&i.Keywords,
			&i.Language,
			&i.Layout,
			&i.Leadershipskills,
			&i.Life,
			&i.Loyalty,
			&i.Manacost,
			&i.Manavalue,
			&i.Name,
			&i.Number,
			&i.Originalprintings,
			&i.Originalreleasedate,
			&i.Originaltext,
			&i.Otherfaceids,
			&i.Power,
			&i.Printedname,
			&i.Printedtext,
			&i.Printedtype,
			&i.Printings,
			&i.Producedmana,
			&i.Promotypes,
			&i.Rarity,
			&i.Rebalancedprintings,
			&i.Relatedcards,
			&i.Securitystamp,
			&i.Setcode,
			&i.Side,
			&i.Signature,
			&i.Skuids,
			&i.Sourceproducts,
			&i.Subsets,
			&i.Subtypes,
			&i.Supertypes,
			&i.Text,
			&i.Toughness,
			&i.Type,
			&i.Types,
			&i.Uuid,
			&i.Variations,
			&i.Watermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardsByRarity = `-- name: GetCardsByRarity :many
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards WHERE rarity = ? LIMIT ? OFFSET ?
`

type GetCardsByRarityParams struct {
	Rarity sql.NullString
	Limit  int64
	Offset int64
}

func (q *Queries) GetCardsByRarity(ctx context.Context, arg GetCardsByRarityParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getCardsByRarity, arg.Rarity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.Artist,
			&i.Artistids,
			&i.Asciiname,
			&i.Attractionlights,
			&i.Availability,
			&i.Boostertypes,
			&i.Bordercolor,
			&i.Cardparts,
			&i.Coloridentity,
			&i.Colorindicator,
			&i.Colors,
			&i.Defense,
			&i.Dueldeck,
			&i.Edhrecrank,
			&i.Edhrecsaltiness,
			&i.Faceconvertedmanacost,
			&i.Faceflavorname,
			&i.Facemanavalue,
			&i.Facename,
			&i.Faceprintedname,
			&i.Finishes,
			&i.Flavorname,
			&i.Flavortext,
			&i.Frameeffects,
			&i.Frameversion,
			&i.Hand,
			&i.Hasalternativedecklimit,
			&i.Hascontentwarning,
			&i.Isalternative,
			&i.Isfullart,
			&i.Isfunny,
			&i.Isgamechanger,
			&i.Isonlineonly,
			&i.Isoversized,
			&i.Ispromo,
			&i.Isrebalanced,
			&i.Isreprint,
			&i.Isreserved,
			&i.Isstoryspotlight,
			&i.Istextless,
			&i.Istimeshifted,
			&i.Keywords,
			&i.Language,
			&i.Layout,
			&i.Leadershipskills,
			&i.Life,
			&i.Loyalty,
			&i.Manacost,
			&i.Manavalue,
			&i.Name,
			&i.Number,
			&i.Originalprintings,
			&i.Originalreleasedate,
			&i.Originaltext,
			&i.Otherfaceids,
			&i.Power,
			&i.Printedname,
			&i.Printedtext,
			&i.Printedtype,
			&i.Printings,
			&i.Producedmana,
			&i.Promotypes,
			&i.Rarity,
			&i.Rebalancedprintings,
			&i.Relatedcards,
			&i.Securitystamp,
			&i.Setcode,
			&i.Side,
			&i.Signature,
			&i.Skuids,
			&i.Sourceproducts,
			&i.Subsets,
			&i.Subtypes,
			&i.Supertypes,
			&i.Text,
			&i.Toughness,
			&i.Type,
			&i.Types,
			&i.Uuid,
			&i.Variations,
			&i.Watermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardsBySetCode = `-- name: GetCardsBySetCode :many
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards WHERE setcode = ?
`

func (q *Queries) GetCardsBySetCode(ctx context.Context, setcode sql.NullString) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getCardsBySetCode, setcode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.Artist,
			&i.Artistids,
			&i.Asciiname,
			&i.Attractionlights,
			&i.Availability,
			&i.Boostertypes,
			&i.Bordercolor,
			&i.Cardparts,
			&i.Coloridentity,
			&i.Colorindicator,
			&i.Colors,
			&i.Defense,
			&i.Dueldeck,
			&i.Edhrecrank,
			&i.Edhrecsaltiness,
			&i.Faceconvertedmanacost,
			&i.Faceflavorname,
			&i.Facemanavalue,
			&i.Facename,
			&i.Faceprintedname,
			&i.Finishes,
			&i.Flavorname,
			&i.Flavortext,
			&i.Frameeffects,
			&i.Frameversion,
			&i.Hand,
			&i.Hasalternativedecklimit,
			&i.Hascontentwarning,
			&i.Isalternative,
			&i.Isfullart,
			&i.Isfunny,
			&i.Isgamechanger,
			&i.Isonlineonly,
			&i.Isoversized,
			&i.Ispromo,
			&i.Isrebalanced,
			&i.Isreprint,
			&i.Isreserved,
			&i.Isstoryspotlight,
			&i.Istextless,
			&i.Istimeshifted,
			&i.Keywords,
			&i.Language,
			&i.Layout,
			&i.Leadershipskills,
			&i.Life,
			&i.Loyalty,
			&i.Manacost,
			&i.Manavalue,
			&i.Name,
			&i.Number,
			&i.Originalprintings,
			&i.Originalreleasedate,
			&i.Originaltext,
			&i.Otherfaceids,
			&i.Power,
			&i.Printedname,
			&i.Printedtext,
			&i.Printedtype,
			&i.Printings,
			&i.Producedmana,
			&i.Promotypes,
			&i.Rarity,
			&i.Rebalancedprintings,
			&i.Relatedcards,
			&i.Securitystamp,
			&i.Setcode,
			&i.Side,
			&i.Signature,
			&i.Skuids,
			&i.Sourceproducts,
			&i.Subsets,
			&i.Subtypes,
			&i.Supertypes,
			&i.Text,
			&i.Toughness,
			&i.Type,
			&i.Types,
			&i.Uuid,
			&i.Variations,
			&i.Watermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCards = `-- name: ListAllCards :many
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards LIMIT ? OFFSET ?
`

type ListAllCardsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListAllCards(ctx context.Context, arg ListAllCardsParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listAllCards, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.Artist,
			&i.Artistids,
			&i.Asciiname,
			&i.Attractionlights,
			&i.Availability,
			&i.Boostertypes,
			&i.Bordercolor,
			&i.Cardparts,
			&i.Coloridentity,
			&i.Colorindicator,
			&i.Colors,
			&i.Defense,
			&i.Dueldeck,
			&i.Edhrecrank,
			&i.Edhrecsaltiness,
			&i.Faceconvertedmanacost,
			&i.Faceflavorname,
			&i.Facemanavalue,
			&i.Facename,
			&i.Faceprintedname,
			&i.Finishes,
			&i.Flavorname,
			&i.Flavortext,
			&i.Frameeffects,
			&i.Frameversion,
			&i.Hand,
			&i.Hasalternativedecklimit,
			&i.Hascontentwarning,
			&i.Isalternative,
			&i.Isfullart,
			&i.Isfunny,
			&i.Isgamechanger,
			&i.Isonlineonly,
			&i.Isoversized,
			&i.Ispromo,
			&i.Isrebalanced,
			&i.Isreprint,
			&i.Isreserved,
			&i.Isstoryspotlight,
			&i.Istextless,
			&i.Istimeshifted,
			&i.Keywords,
			&i.Language,
			&i.Layout,
			&i.Leadershipskills,
			&i.Life,
			&i.Loyalty,
			&i.Manacost,
			&i.Manavalue,
			&i.Name,
			&i.Number,
			&i.Originalprintings,
			&i.Originalreleasedate,
			&i.Originaltext,
			&i.Otherfaceids,
			&i.Power,
			&i.Printedname,
			&i.Printedtext,
			&i.Printedtype,
			&i.Printings,
			&i.Producedmana,
			&i.Promotypes,
			&i.Rarity,
			&i.Rebalancedprintings,
			&i.Relatedcards,
			&i.Securitystamp,
			&i.Setcode,
			&i.Side,
			&i.Signature,
			&i.Skuids,
			&i.Sourceproducts,
			&i.Subsets,
			&i.Subtypes,
			&i.Supertypes,
			&i.Text,
			&i.Toughness,
			&i.Type,
			&i.Types,
			&i.Uuid,
			&i.Variations,
			&i.Watermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCards = `-- name: SearchCards :many
SELECT artist, artistids, asciiname, attractionlights, availability, boostertypes, bordercolor, cardparts, coloridentity, colorindicator, colors, defense, dueldeck, edhrecrank, edhrecsaltiness, faceconvertedmanacost, faceflavorname, facemanavalue, facename, faceprintedname, finishes, flavorname, flavortext, frameeffects, frameversion, hand, hasalternativedecklimit, hascontentwarning, isalternative, isfullart, isfunny, isgamechanger, isonlineonly, isoversized, ispromo, isrebalanced, isreprint, isreserved, isstoryspotlight, istextless, istimeshifted, keywords, language, layout, leadershipskills, life, loyalty, manacost, manavalue, name, number, originalprintings, originalreleasedate, originaltext, otherfaceids, power, printedname, printedtext, printedtype, printings, producedmana, promotypes, rarity, rebalancedprintings, relatedcards, securitystamp, setcode, side, signature, skuids, sourceproducts, subsets, subtypes, supertypes, text, toughness, type, types, uuid, variations, watermark FROM cards c
WHERE 1=1
    AND (?1 IS NULL OR artist LIKE ?1)
    AND (?2 IS NULL OR artistIds LIKE ?2)
    AND (?3 IS NULL OR asciiName LIKE ?3)
    AND (?4 IS NULL OR attractionLights LIKE ?4)
    AND (?5 IS NULL OR availability LIKE ?5)
    AND (?6 IS NULL OR boosterTypes LIKE ?6)
    AND (?7 IS NULL OR borderColor LIKE ?7)
    AND (?8 IS NULL OR cardParts LIKE ?8)
    AND (?9 IS NULL OR colorIdentity LIKE ?9)
    AND (?10 IS NULL OR colorIndicator LIKE ?10)
    AND (?11 IS NULL OR colors LIKE ?11)
    AND (?12 IS NULL OR defense LIKE ?12)
    AND (?13 IS NULL OR duelDeck LIKE ?13)
    AND (?14 IS NULL OR edhrecRank = ?14)
    AND (?15 IS NULL OR edhrecSaltiness = ?15)
    AND (?16 IS NULL OR faceConvertedManaCost = ?16)
    AND (?17 IS NULL OR faceFlavorName LIKE ?17)
    AND (?18 IS NULL OR faceManaValue = ?18)
    AND (?19 IS NULL OR faceName LIKE ?19)
    AND (?20 IS NULL OR facePrintedName LIKE ?20)
    AND (?21 IS NULL OR finishes LIKE ?21)
    AND (?22 IS NULL OR flavorName LIKE ?22)
    AND (?23 IS NULL OR flavorText LIKE ?23)
    AND (?24 IS NULL OR frameEffects LIKE ?24)
    AND (?25 IS NULL OR frameVersion LIKE ?25)
    AND (?26 IS NULL OR hand LIKE ?26)
    AND (?27 IS NULL OR hasAlternativeDeckLimit = ?27)
    AND (?28 IS NULL OR hasContentWarning = ?28)
    AND (?29 IS NULL OR isAlternative = ?29)
    AND (?30 IS NULL OR isFullArt = ?30)
    AND (?31 IS NULL OR isFunny = ?31)
    AND (?32 IS NULL OR isGameChanger = ?32)
    AND (?33 IS NULL OR isOnlineOnly = ?33)
    AND (?34 IS NULL OR isOversized = ?34)
    AND (?35 IS NULL OR isPromo = ?35)
    AND (?36 IS NULL OR isRebalanced = ?36)
    AND (?37 IS NULL OR isReprint = ?37)
    AND (?38 IS NULL OR isReserved = ?38)
    AND (?39 IS NULL OR isStorySpotlight = ?39)
    AND (?40 IS NULL OR isTextless = ?40)
    AND (?41 IS NULL OR isTimeshifted = ?41)
    AND (?42 IS NULL OR keywords LIKE ?42)
    AND (?43 IS NULL OR language LIKE ?43)
    AND (?44 IS NULL OR layout LIKE ?44)
    AND (?45 IS NULL OR leadershipSkills LIKE ?45)
    AND (?46 IS NULL OR life LIKE ?46)
    AND (?47 IS NULL OR loyalty LIKE ?47)
    AND (?48 IS NULL OR manaCost LIKE ?48)
    AND (?49 IS NULL OR manaValue = ?49)
    AND (?50 IS NULL OR name LIKE ?50)
    AND (?51 IS NULL OR number LIKE ?51)
    AND (?52 IS NULL OR originalPrintings LIKE ?52)
    AND (?53 IS NULL OR originalReleaseDate LIKE ?53)
    AND (?54 IS NULL OR originalText LIKE ?54)
    AND (?55 IS NULL OR otherFaceIds LIKE ?55)
    AND (?56 IS NULL OR power LIKE ?56)
    AND (?57 IS NULL OR printedName LIKE ?57)
    AND (?58 IS NULL OR printedText LIKE ?58)
    AND (?59 IS NULL OR printedType LIKE ?59)
    AND (?60 IS NULL OR printings LIKE ?60)
    AND (?61 IS NULL OR producedMana LIKE ?61)
    AND (?62 IS NULL OR promoTypes LIKE ?62)
    AND (?63 IS NULL OR rarity LIKE ?63)
    AND (?64 IS NULL OR rebalancedPrintings LIKE ?64)
    AND (?65 IS NULL OR relatedCards LIKE ?65)
    AND (?66 IS NULL OR securityStamp LIKE ?66)
    AND (?67 IS NULL OR setCode LIKE ?67)
    AND (?68 IS NULL OR side LIKE ?68)
    AND (?69 IS NULL OR signature LIKE ?69)
    AND (?70 IS NULL OR skuIds LIKE ?70)
    AND (?71 IS NULL OR sourceProducts LIKE ?71)
    AND (?72 IS NULL OR subsets LIKE ?72)
    AND (?73 IS NULL OR subtypes LIKE ?73)
    AND (?74 IS NULL OR supertypes LIKE ?74)
    AND (?75 IS NULL OR text LIKE ?75)
    AND (?76 IS NULL OR toughness LIKE ?76)
    AND (?77 IS NULL OR type LIKE ?77)
    AND (?78 IS NULL OR types LIKE ?78)
    AND (?79 IS NULL OR uuid LIKE ?79)
    AND (?80 IS NULL OR variations LIKE ?80)
    AND (?81 IS NULL OR watermark LIKE ?81)
ORDER BY c.name ASC
LIMIT ?83 OFFSET ?82
`

type SearchCardsParams struct {
	Artist                  interface{}
	ArtistIds               interface{}
	AsciiName               interface{}
	AttractionLights        interface{}
	Availability            interface{}
	BoosterTypes            interface{}
	BorderColor             interface{}
	CardParts               interface{}
	ColorIdentity           interface{}
	ColorIndicator          interface{}
	Colors                  interface{}
	Defense                 interface{}
	DuelDeck                interface{}
	EdhrecRank              interface{}
	EdhrecSaltiness         interface{}
	FaceConvertedManaCost   interface{}
	FaceFlavorName          interface{}
	FaceManaValue           interface{}
	FaceName                interface{}
	FacePrintedName         interface{}
	Finishes                interface{}
	FlavorName              interface{}
	FlavorText              interface{}
	FrameEffects            interface{}
	FrameVersion            interface{}
	Hand                    interface{}
	HasAlternativeDeckLimit interface{}
	HasContentWarning       interface{}
	IsAlternative           interface{}
	IsFullArt               interface{}
	IsFunny                 interface{}
	IsGameChanger           interface{}
	IsOnlineOnly            interface{}
	IsOversized             interface{}
	IsPromo                 interface{}
	IsRebalanced            interface{}
	IsReprint               interface{}
	IsReserved              interface{}
	IsStorySpotlight        interface{}
	IsTextless              interface{}
	IsTimeshifted           interface{}
	Keywords                interface{}
	Language                interface{}
	Layout                  interface{}
	LeadershipSkills        interface{}
	Life                    interface{}
	Loyalty                 interface{}
	ManaCost                interface{}
	ManaValue               interface{}
	Name                    interface{}
	Number                  interface{}
	OriginalPrintings       interface{}
	OriginalReleaseDate     interface{}
	OriginalText            interface{}
	OtherFaceIds            interface{}
	Power                   interface{}
	PrintedName             interface{}
	PrintedText             interface{}
	PrintedType             interface{}
	Printings               interface{}
	ProducedMana            interface{}
	PromoTypes              interface{}
	Rarity                  interface{}
	RebalancedPrintings     interface{}
	RelatedCards            interface{}
	SecurityStamp           interface{}
	SetCode                 interface{}
	Side                    interface{}
	Signature               interface{}
	SkuIds                  interface{}
	SourceProducts          interface{}
	Subsets                 interface{}
	Subtypes                interface{}
	Supertypes              interface{}
	Text                    interface{}
	Toughness               interface{}
	Type                    interface{}
	Types                   interface{}
	Uuid                    interface{}
	Variations              interface{}
	Watermark               interface{}
	Offset                  int64
	Limit                   int64
}

func (q *Queries) SearchCards(ctx context.Context, arg SearchCardsParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, searchCards,
		arg.Artist,
		arg.ArtistIds,
		arg.AsciiName,
		arg.AttractionLights,
		arg.Availability,
		arg.BoosterTypes,
		arg.BorderColor,
		arg.CardParts,
		arg.ColorIdentity,
		arg.ColorIndicator,
		arg.Colors,
		arg.Defense,
		arg.DuelDeck,
		arg.EdhrecRank,
		arg.EdhrecSaltiness,
		arg.FaceConvertedManaCost,
		arg.FaceFlavorName,
		arg.FaceManaValue,
		arg.FaceName,
		arg.FacePrintedName,
		arg.Finishes,
		arg.FlavorName,
		arg.FlavorText,
		arg.FrameEffects,
		arg.FrameVersion,
		arg.Hand,
		arg.HasAlternativeDeckLimit,
		arg.HasContentWarning,
		arg.IsAlternative,
		arg.IsFullArt,
		arg.IsFunny,
		arg.IsGameChanger,
		arg.IsOnlineOnly,
		arg.IsOversized,
		arg.IsPromo,
		arg.IsRebalanced,
		arg.IsReprint,
		arg.IsReserved,
		arg.IsStorySpotlight,
		arg.IsTextless,
		arg.IsTimeshifted,
		arg.Keywords,
		arg.Language,
		arg.Layout,
		arg.LeadershipSkills,
		arg.Life,
		arg.Loyalty,
		arg.ManaCost,
		arg.ManaValue,
		arg.Name,
		arg.Number,
		arg.OriginalPrintings,
		arg.OriginalReleaseDate,
		arg.OriginalText,
		arg.OtherFaceIds,
		arg.Power,
		arg.PrintedName,
		arg.PrintedText,
		arg.PrintedType,
		arg.Printings,
		arg.ProducedMana,
		arg.PromoTypes,
		arg.Rarity,
		arg.RebalancedPrintings,
		arg.RelatedCards,
		arg.SecurityStamp,
		arg.SetCode,
		arg.Side,
		arg.Signature,
		arg.SkuIds,
		arg.SourceProducts,
		arg.Subsets,
		arg.Subtypes,
		arg.Supertypes,
		arg.Text,
		arg.Toughness,
		arg.Type,
		arg.Types,
		arg.Uuid,
		arg.Variations,
		arg.Watermark,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.Artist,
			&i.Artistids,
			&i.Asciiname,
			&i.Attractionlights,
			&i.Availability,
			&i.Boostertypes,
			&i.Bordercolor,
			&i.Cardparts,
			&i.Coloridentity,
			&i.Colorindicator,
			&i.Colors,
			&i.Defense,
			&i.Dueldeck,
			&i.Edhrecrank,
			&i.Edhrecsaltiness,
			&i.Faceconvertedmanacost,
			&i.Faceflavorname,
			&i.Facemanavalue,
			&i.Facename,
			&i.Faceprintedname,
			&i.Finishes,
			&i.Flavorname,
			&i.Flavortext,
			&i.Frameeffects,
			&i.Frameversion,
			&i.Hand,
			&i.Hasalternativedecklimit,
			&i.Hascontentwarning,
			&i.Isalternative,
			&i.Isfullart,
			&i.Isfunny,
			&i.Isgamechanger,
			&i.Isonlineonly,
			&i.Isoversized,
			&i.Ispromo,
			&i.Isrebalanced,
			&i.Isreprint,
			&i.Isreserved,
			&i.Isstoryspotlight,
			&i.Istextless,
			&i.Istimeshifted,
			&i.Keywords,
			&i.Language,
			&i.Layout,
			&i.Leadershipskills,
			&i.Life,
			&i.Loyalty,
			&i.Manacost,
			&i.Manavalue,
			&i.Name,
			&i.Number,
			&i.Originalprintings,
			&i.Originalreleasedate,
			&i.Originaltext,
			&i.Otherfaceids,
			&i.Power,
			&i.Printedname,
			&i.Printedtext,
			&i.Printedtype,
			&i.Printings,
			&i.Producedmana,
			&i.Promotypes,
			&i.Rarity,
			&i.Rebalancedprintings,
			&i.Relatedcards,
			&i.Securitystamp,
			&i.Setcode,
			&i.Side,
			&i.Signature,
			&i.Skuids,
			&i.Sourceproducts,
			&i.Subsets,
			&i.Subtypes,
			&i.Supertypes,
			&i.Text,
			&i.Toughness,
			&i.Type,
			&i.Types,
			&i.Uuid,
			&i.Variations,
			&i.Watermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
