// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cards

import (
	"database/sql"
)

type Card struct {
	Artist                  sql.NullString
	Artistids               sql.NullString
	Asciiname               sql.NullString
	Attractionlights        sql.NullString
	Availability            sql.NullString
	Boostertypes            sql.NullString
	Bordercolor             sql.NullString
	Cardparts               sql.NullString
	Coloridentity           sql.NullString
	Colorindicator          sql.NullString
	Colors                  sql.NullString
	Defense                 sql.NullString
	Dueldeck                sql.NullString
	Edhrecrank              sql.NullInt64
	Edhrecsaltiness         sql.NullFloat64
	Faceconvertedmanacost   sql.NullFloat64
	Faceflavorname          sql.NullString
	Facemanavalue           sql.NullFloat64
	Facename                sql.NullString
	Faceprintedname         sql.NullString
	Finishes                sql.NullString
	Flavorname              sql.NullString
	Flavortext              sql.NullString
	Frameeffects            sql.NullString
	Frameversion            sql.NullString
	Hand                    sql.NullString
	Hasalternativedecklimit sql.NullBool
	Hascontentwarning       sql.NullBool
	Isalternative           sql.NullBool
	Isfullart               sql.NullBool
	Isfunny                 sql.NullBool
	Isgamechanger           sql.NullBool
	Isonlineonly            sql.NullBool
	Isoversized             sql.NullBool
	Ispromo                 sql.NullBool
	Isrebalanced            sql.NullBool
	Isreprint               sql.NullBool
	Isreserved              sql.NullBool
	Isstoryspotlight        sql.NullBool
	Istextless              sql.NullBool
	Istimeshifted           sql.NullBool
	Keywords                sql.NullString
	Language                sql.NullString
	Layout                  sql.NullString
	Leadershipskills        sql.NullString
	Life                    sql.NullString
	Loyalty                 sql.NullString
	Manacost                sql.NullString
	Manavalue               sql.NullFloat64
	Name                    sql.NullString
	Number                  sql.NullString
	Originalprintings       sql.NullString
	Originalreleasedate     sql.NullString
	Originaltext            sql.NullString
	Otherfaceids            sql.NullString
	Power                   sql.NullString
	Printedname             sql.NullString
	Printedtext             sql.NullString
	Printedtype             sql.NullString
	Printings               sql.NullString
	Producedmana            sql.NullString
	Promotypes              sql.NullString
	Rarity                  sql.NullString
	Rebalancedprintings     sql.NullString
	Relatedcards            sql.NullString
	Securitystamp           sql.NullString
	Setcode                 sql.NullString
	Side                    sql.NullString
	Signature               sql.NullString
	Skuids                  sql.NullString
	Sourceproducts          sql.NullString
	Subsets                 sql.NullString
	Subtypes                sql.NullString
	Supertypes              sql.NullString
	Text                    sql.NullString
	Toughness               sql.NullString
	Type                    sql.NullString
	Types                   sql.NullString
	Uuid                    sql.NullString
	Variations              sql.NullString
	Watermark               sql.NullString
}

type Cardforeigndatum struct {
	Uuid         sql.NullString
	Facename     sql.NullString
	Skuids       sql.NullString
	Flavortext   sql.NullString
	Identifiers  sql.NullString
	Language     sql.NullString
	Multiverseid sql.NullInt64
	Name         sql.NullString
	Text         sql.NullString
	Type         sql.NullString
}

type Cardidentifier struct {
	Uuid                              sql.NullString
	Scryfallid                        sql.NullString
	Scryfalloracleid                  sql.NullString
	Scryfallillustrationid            sql.NullString
	Scryfallcardbackid                sql.NullString
	Mcmid                             sql.NullString
	Mcmmetaid                         sql.NullString
	Mtgarenaid                        sql.NullString
	Mtgoid                            sql.NullString
	Mtgofoilid                        sql.NullString
	Multiverseid                      sql.NullString
	Tcgplayerproductid                sql.NullString
	Tcgplayeretchedproductid          sql.NullString
	Tcgplayeralternativefoilproductid sql.NullString
	Cardkingdomid                     sql.NullString
	Cardkingdomfoilid                 sql.NullString
	Cardkingdometchedid               sql.NullString
	Cardsphereid                      sql.NullString
	Cardspherefoilid                  sql.NullString
	Deckboxid                         sql.NullString
	Mtgjsonfoilversionid              sql.NullString
	Mtgjsonnonfoilversionid           sql.NullString
	Mtgjsonv4id                       sql.NullString
}

type Cardlegality struct {
	Uuid            sql.NullString
	Alchemy         sql.NullString
	Brawl           sql.NullString
	Commander       sql.NullString
	Duel            sql.NullString
	Future          sql.NullString
	Gladiator       sql.NullString
	Historic        sql.NullString
	Legacy          sql.NullString
	Modern          sql.NullString
	Oathbreaker     sql.NullString
	Oldschool       sql.NullString
	Pauper          sql.NullString
	Paupercommander sql.NullString
	Penny           sql.NullString
	Pioneer         sql.NullString
	Predh           sql.NullString
	Premodern       sql.NullString
	Standard        sql.NullString
	Standardbrawl   sql.NullString
	Timeless        sql.NullString
	Vintage         sql.NullString
}

type Cardpurchaseurl struct {
	Uuid                     sql.NullString
	Cardkingdom              sql.NullString
	Cardkingdomfoil          sql.NullString
	Cardkingdometched        sql.NullString
	Cardmarket               sql.NullString
	Cardmarketfoil           sql.NullString
	Tcgplayer                sql.NullString
	Tcgplayeretched          sql.NullString
	Tcgplayeralternativefoil sql.NullString
}

type Cardruling struct {
	Uuid sql.NullString
	Date sql.NullTime
	Text sql.NullString
}

type Set struct {
	Code             sql.NullString
	Mtgocode         sql.NullString
	Name             sql.NullString
	Releasedate      sql.NullString
	Type             sql.NullString
	Isonlineonly     sql.NullBool
	Isfoilonly       sql.NullBool
	Isnonfoilonly    sql.NullBool
	Parentcode       sql.NullString
	Totalsetsize     sql.NullInt64
	Basesetsize      sql.NullInt64
	Keyrunecode      sql.NullString
	Ispartialpreview sql.NullBool
	Isforeignonly    sql.NullBool
	Ispaperonly      sql.NullBool
	Languages        sql.NullString
	Tcgplayergroupid sql.NullInt64
	Tokensetcode     sql.NullString
	Mcmid            sql.NullInt64
	Mcmname          sql.NullString
	Mcmidextras      sql.NullInt64
	Block            sql.NullString
}
